//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alemana.Nucleo.Common.WsSuser2Roles {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nucleo.alemana.cl/", ConfigurationName="WsSuser2Roles.Wssuser2rolesWeb")]
    public interface Wssuser2rolesWeb {
        
        // CODEGEN: El parámetro 'spsusFuncSuserXRutResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Common.WsSuser2Roles.spsusFuncSuserXRutResponse spsusFuncSuserXRut(Alemana.Nucleo.Common.WsSuser2Roles.spsusFuncSuserXRutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsSuser2Roles.spsusFuncSuserXRutResponse> spsusFuncSuserXRutAsync(Alemana.Nucleo.Common.WsSuser2Roles.spsusFuncSuserXRutRequest request);
        
        // CODEGEN: El parámetro 'spsusRolesSuserXRutResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Common.WsSuser2Roles.spsusRolesSuserXRutResponse spsusRolesSuserXRut(Alemana.Nucleo.Common.WsSuser2Roles.spsusRolesSuserXRutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsSuser2Roles.spsusRolesSuserXRutResponse> spsusRolesSuserXRutAsync(Alemana.Nucleo.Common.WsSuser2Roles.spsusRolesSuserXRutRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class SpsusFuncSuserXRutResult : ProcedureResult {
        
        private SpsusFuncSuserXRutRol[] rolesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("roles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public SpsusFuncSuserXRutRol[] roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
                this.RaisePropertyChanged("roles");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class SpsusFuncSuserXRutRol : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string funcionalidadDescField;
        
        private decimal funcionalidadIdField;
        
        private bool funcionalidadIdFieldSpecified;
        
        private string grupoDescField;
        
        private decimal grupoIdField;
        
        private bool grupoIdFieldSpecified;
        
        private string rolDescField;
        
        private decimal rolIdField;
        
        private bool rolIdFieldSpecified;
        
        private string rutField;
        
        private string sistemaDescField;
        
        private decimal sistemaIdField;
        
        private bool sistemaIdFieldSpecified;
        
        private string usuarioDescField;
        
        private decimal usuarioIdField;
        
        private bool usuarioIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string funcionalidadDesc {
            get {
                return this.funcionalidadDescField;
            }
            set {
                this.funcionalidadDescField = value;
                this.RaisePropertyChanged("funcionalidadDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal funcionalidadId {
            get {
                return this.funcionalidadIdField;
            }
            set {
                this.funcionalidadIdField = value;
                this.RaisePropertyChanged("funcionalidadId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool funcionalidadIdSpecified {
            get {
                return this.funcionalidadIdFieldSpecified;
            }
            set {
                this.funcionalidadIdFieldSpecified = value;
                this.RaisePropertyChanged("funcionalidadIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string grupoDesc {
            get {
                return this.grupoDescField;
            }
            set {
                this.grupoDescField = value;
                this.RaisePropertyChanged("grupoDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal grupoId {
            get {
                return this.grupoIdField;
            }
            set {
                this.grupoIdField = value;
                this.RaisePropertyChanged("grupoId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grupoIdSpecified {
            get {
                return this.grupoIdFieldSpecified;
            }
            set {
                this.grupoIdFieldSpecified = value;
                this.RaisePropertyChanged("grupoIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string rolDesc {
            get {
                return this.rolDescField;
            }
            set {
                this.rolDescField = value;
                this.RaisePropertyChanged("rolDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal rolId {
            get {
                return this.rolIdField;
            }
            set {
                this.rolIdField = value;
                this.RaisePropertyChanged("rolId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rolIdSpecified {
            get {
                return this.rolIdFieldSpecified;
            }
            set {
                this.rolIdFieldSpecified = value;
                this.RaisePropertyChanged("rolIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string sistemaDesc {
            get {
                return this.sistemaDescField;
            }
            set {
                this.sistemaDescField = value;
                this.RaisePropertyChanged("sistemaDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal sistemaId {
            get {
                return this.sistemaIdField;
            }
            set {
                this.sistemaIdField = value;
                this.RaisePropertyChanged("sistemaId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sistemaIdSpecified {
            get {
                return this.sistemaIdFieldSpecified;
            }
            set {
                this.sistemaIdFieldSpecified = value;
                this.RaisePropertyChanged("sistemaIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string usuarioDesc {
            get {
                return this.usuarioDescField;
            }
            set {
                this.usuarioDescField = value;
                this.RaisePropertyChanged("usuarioDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal usuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
                this.RaisePropertyChanged("usuarioId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioIdSpecified {
            get {
                return this.usuarioIdFieldSpecified;
            }
            set {
                this.usuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("usuarioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class SpsusRolesSuserXRutRol : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rolDescField;
        
        private decimal rolIdField;
        
        private bool rolIdFieldSpecified;
        
        private string rutField;
        
        private string sistemaDescField;
        
        private decimal sistemaIdField;
        
        private bool sistemaIdFieldSpecified;
        
        private string usuarioDescField;
        
        private decimal usuarioIdField;
        
        private bool usuarioIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rolDesc {
            get {
                return this.rolDescField;
            }
            set {
                this.rolDescField = value;
                this.RaisePropertyChanged("rolDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal rolId {
            get {
                return this.rolIdField;
            }
            set {
                this.rolIdField = value;
                this.RaisePropertyChanged("rolId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rolIdSpecified {
            get {
                return this.rolIdFieldSpecified;
            }
            set {
                this.rolIdFieldSpecified = value;
                this.RaisePropertyChanged("rolIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sistemaDesc {
            get {
                return this.sistemaDescField;
            }
            set {
                this.sistemaDescField = value;
                this.RaisePropertyChanged("sistemaDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal sistemaId {
            get {
                return this.sistemaIdField;
            }
            set {
                this.sistemaIdField = value;
                this.RaisePropertyChanged("sistemaId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sistemaIdSpecified {
            get {
                return this.sistemaIdFieldSpecified;
            }
            set {
                this.sistemaIdFieldSpecified = value;
                this.RaisePropertyChanged("sistemaIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string usuarioDesc {
            get {
                return this.usuarioDescField;
            }
            set {
                this.usuarioDescField = value;
                this.RaisePropertyChanged("usuarioDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal usuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
                this.RaisePropertyChanged("usuarioId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioIdSpecified {
            get {
                return this.usuarioIdFieldSpecified;
            }
            set {
                this.usuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("usuarioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpsusRolesSuserXRutResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpsusFuncSuserXRutResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public abstract partial class ProcedureResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class SpsusRolesSuserXRutResult : ProcedureResult {
        
        private SpsusRolesSuserXRutRol[] rolesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("roles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public SpsusRolesSuserXRutRol[] roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
                this.RaisePropertyChanged("roles");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="spsusFuncSuserXRut", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class spsusFuncSuserXRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piUsrRut;
        
        public spsusFuncSuserXRutRequest() {
        }
        
        public spsusFuncSuserXRutRequest(string piUsrRut) {
            this.piUsrRut = piUsrRut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="spsusFuncSuserXRutResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class spsusFuncSuserXRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Common.WsSuser2Roles.SpsusFuncSuserXRutResult spsusFuncSuserXRutResult;
        
        public spsusFuncSuserXRutResponse() {
        }
        
        public spsusFuncSuserXRutResponse(Alemana.Nucleo.Common.WsSuser2Roles.SpsusFuncSuserXRutResult spsusFuncSuserXRutResult) {
            this.spsusFuncSuserXRutResult = spsusFuncSuserXRutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="spsusRolesSuserXRut", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class spsusRolesSuserXRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piUsrRut;
        
        public spsusRolesSuserXRutRequest() {
        }
        
        public spsusRolesSuserXRutRequest(string piUsrRut) {
            this.piUsrRut = piUsrRut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="spsusRolesSuserXRutResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class spsusRolesSuserXRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Common.WsSuser2Roles.SpsusRolesSuserXRutResult spsusRolesSuserXRutResult;
        
        public spsusRolesSuserXRutResponse() {
        }
        
        public spsusRolesSuserXRutResponse(Alemana.Nucleo.Common.WsSuser2Roles.SpsusRolesSuserXRutResult spsusRolesSuserXRutResult) {
            this.spsusRolesSuserXRutResult = spsusRolesSuserXRutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Wssuser2rolesWebChannel : Alemana.Nucleo.Common.WsSuser2Roles.Wssuser2rolesWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Wssuser2rolesWebClient : System.ServiceModel.ClientBase<Alemana.Nucleo.Common.WsSuser2Roles.Wssuser2rolesWeb>, Alemana.Nucleo.Common.WsSuser2Roles.Wssuser2rolesWeb {
        
        public Wssuser2rolesWebClient() {
        }
        
        public Wssuser2rolesWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Wssuser2rolesWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Wssuser2rolesWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Wssuser2rolesWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Common.WsSuser2Roles.spsusFuncSuserXRutResponse Alemana.Nucleo.Common.WsSuser2Roles.Wssuser2rolesWeb.spsusFuncSuserXRut(Alemana.Nucleo.Common.WsSuser2Roles.spsusFuncSuserXRutRequest request) {
            return base.Channel.spsusFuncSuserXRut(request);
        }
        
        public Alemana.Nucleo.Common.WsSuser2Roles.SpsusFuncSuserXRutResult spsusFuncSuserXRut(string piUsrRut) {
            Alemana.Nucleo.Common.WsSuser2Roles.spsusFuncSuserXRutRequest inValue = new Alemana.Nucleo.Common.WsSuser2Roles.spsusFuncSuserXRutRequest();
            inValue.piUsrRut = piUsrRut;
            Alemana.Nucleo.Common.WsSuser2Roles.spsusFuncSuserXRutResponse retVal = ((Alemana.Nucleo.Common.WsSuser2Roles.Wssuser2rolesWeb)(this)).spsusFuncSuserXRut(inValue);
            return retVal.spsusFuncSuserXRutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsSuser2Roles.spsusFuncSuserXRutResponse> Alemana.Nucleo.Common.WsSuser2Roles.Wssuser2rolesWeb.spsusFuncSuserXRutAsync(Alemana.Nucleo.Common.WsSuser2Roles.spsusFuncSuserXRutRequest request) {
            return base.Channel.spsusFuncSuserXRutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsSuser2Roles.spsusFuncSuserXRutResponse> spsusFuncSuserXRutAsync(string piUsrRut) {
            Alemana.Nucleo.Common.WsSuser2Roles.spsusFuncSuserXRutRequest inValue = new Alemana.Nucleo.Common.WsSuser2Roles.spsusFuncSuserXRutRequest();
            inValue.piUsrRut = piUsrRut;
            return ((Alemana.Nucleo.Common.WsSuser2Roles.Wssuser2rolesWeb)(this)).spsusFuncSuserXRutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Common.WsSuser2Roles.spsusRolesSuserXRutResponse Alemana.Nucleo.Common.WsSuser2Roles.Wssuser2rolesWeb.spsusRolesSuserXRut(Alemana.Nucleo.Common.WsSuser2Roles.spsusRolesSuserXRutRequest request) {
            return base.Channel.spsusRolesSuserXRut(request);
        }
        
        public Alemana.Nucleo.Common.WsSuser2Roles.SpsusRolesSuserXRutResult spsusRolesSuserXRut(string piUsrRut) {
            Alemana.Nucleo.Common.WsSuser2Roles.spsusRolesSuserXRutRequest inValue = new Alemana.Nucleo.Common.WsSuser2Roles.spsusRolesSuserXRutRequest();
            inValue.piUsrRut = piUsrRut;
            Alemana.Nucleo.Common.WsSuser2Roles.spsusRolesSuserXRutResponse retVal = ((Alemana.Nucleo.Common.WsSuser2Roles.Wssuser2rolesWeb)(this)).spsusRolesSuserXRut(inValue);
            return retVal.spsusRolesSuserXRutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsSuser2Roles.spsusRolesSuserXRutResponse> Alemana.Nucleo.Common.WsSuser2Roles.Wssuser2rolesWeb.spsusRolesSuserXRutAsync(Alemana.Nucleo.Common.WsSuser2Roles.spsusRolesSuserXRutRequest request) {
            return base.Channel.spsusRolesSuserXRutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsSuser2Roles.spsusRolesSuserXRutResponse> spsusRolesSuserXRutAsync(string piUsrRut) {
            Alemana.Nucleo.Common.WsSuser2Roles.spsusRolesSuserXRutRequest inValue = new Alemana.Nucleo.Common.WsSuser2Roles.spsusRolesSuserXRutRequest();
            inValue.piUsrRut = piUsrRut;
            return ((Alemana.Nucleo.Common.WsSuser2Roles.Wssuser2rolesWeb)(this)).spsusRolesSuserXRutAsync(inValue);
        }
    }
}
