//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.alemana.cl/Enterprise/Tools/services/AL_INTEGRACION_NUCLEO.1", ConfigurationName="WsIntegracionCRM.AL_INTEGRACION_NUCLEO_PortType")]
    public interface AL_INTEGRACION_NUCLEO_PortType {
        
        // CODEGEN: Generating message contract since the operation AL_CONS_REQXMED_DETALLE is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="AL_CONS_REQXMED_DETALLE.v1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CRESV1 AL_CONS_REQXMED_DETALLE(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CREQV1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AL_CONS_REQXMED_DETALLE.v1", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CRESV1> AL_CONS_REQXMED_DETALLEAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CREQV1 request);
        
        // CODEGEN: Generating message contract since the operation AL_CONS_REQXMED_RESUMEN is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="AL_CONS_REQXMED_RESUMEN.v1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CRESV1 AL_CONS_REQXMED_RESUMEN(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CREQV1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AL_CONS_REQXMED_RESUMEN.v1", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CRESV1> AL_CONS_REQXMED_RESUMENAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CREQV1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Enterprise/Tools/schemas/AL_CONS_REQXMED_DETALLE_CREQ.V1")]
    public partial class AL_CONS_REQXMED_DETALLE_CREQType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AL_CONS_REQXMED_DETALLE_PREQ_TypeShape aL_CONS_REQXMED_DETALLE_PREQField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AL_CONS_REQXMED_DETALLE_PREQ_TypeShape AL_CONS_REQXMED_DETALLE_PREQ {
            get {
                return this.aL_CONS_REQXMED_DETALLE_PREQField;
            }
            set {
                this.aL_CONS_REQXMED_DETALLE_PREQField = value;
                this.RaisePropertyChanged("AL_CONS_REQXMED_DETALLE_PREQ");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Enterprise/Tools/schemas/AL_CONS_REQXMED_DETALLE_PREQ.V1")]
    public partial class AL_CONS_REQXMED_DETALLE_PREQ_TypeShape : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AL_CASEID_WKIMsgDataRecord_TypeShape aL_CASEID_WKIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AL_CASEID_WKIMsgDataRecord_TypeShape AL_CASEID_WKI {
            get {
                return this.aL_CASEID_WKIField;
            }
            set {
                this.aL_CASEID_WKIField = value;
                this.RaisePropertyChanged("AL_CASEID_WKI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Enterprise/Tools/schemas/AL_CONS_REQXMED_DETALLE_PREQ.V1")]
    public partial class AL_CASEID_WKIMsgDataRecord_TypeShape : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cASE_IDField;
        
        private string classField;
        
        public AL_CASEID_WKIMsgDataRecord_TypeShape() {
            this.classField = "R";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string CASE_ID {
            get {
                return this.cASE_IDField;
            }
            set {
                this.cASE_IDField = value;
                this.RaisePropertyChanged("CASE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Enterprise/Tools/schemas/AL_CONS_REQXMED_RESUMEN_PRES.V1")]
    public partial class AL_REQCDRES_WKIMsgDataRecord_TypeShape : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cASE_IDField;
        
        private string pERSON_IDField;
        
        private string dESCR_TIPO_CASOField;
        
        private string rOW_ADDED_DTTMField;
        
        private string aL_ESTADO_SECUNDARField;
        
        private string oBSERVACIONESField;
        
        private string classField;
        
        public AL_REQCDRES_WKIMsgDataRecord_TypeShape() {
            this.classField = "R";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string CASE_ID {
            get {
                return this.cASE_IDField;
            }
            set {
                this.cASE_IDField = value;
                this.RaisePropertyChanged("CASE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PERSON_ID {
            get {
                return this.pERSON_IDField;
            }
            set {
                this.pERSON_IDField = value;
                this.RaisePropertyChanged("PERSON_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DESCR_TIPO_CASO {
            get {
                return this.dESCR_TIPO_CASOField;
            }
            set {
                this.dESCR_TIPO_CASOField = value;
                this.RaisePropertyChanged("DESCR_TIPO_CASO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ROW_ADDED_DTTM {
            get {
                return this.rOW_ADDED_DTTMField;
            }
            set {
                this.rOW_ADDED_DTTMField = value;
                this.RaisePropertyChanged("ROW_ADDED_DTTM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AL_ESTADO_SECUNDAR {
            get {
                return this.aL_ESTADO_SECUNDARField;
            }
            set {
                this.aL_ESTADO_SECUNDARField = value;
                this.RaisePropertyChanged("AL_ESTADO_SECUNDAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OBSERVACIONES {
            get {
                return this.oBSERVACIONESField;
            }
            set {
                this.oBSERVACIONESField = value;
                this.RaisePropertyChanged("OBSERVACIONES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Enterprise/Tools/schemas/AL_CONS_REQXMED_RESUMEN_PRES.V1")]
    public partial class AL_CONS_REQXMED_RESUMEN_PRES_TypeShape : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AL_REQCDRES_WKIMsgDataRecord_TypeShape aL_REQCDRES_WKIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AL_REQCDRES_WKIMsgDataRecord_TypeShape AL_REQCDRES_WKI {
            get {
                return this.aL_REQCDRES_WKIField;
            }
            set {
                this.aL_REQCDRES_WKIField = value;
                this.RaisePropertyChanged("AL_REQCDRES_WKI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Enterprise/Tools/schemas/AL_CONS_REQXMED_RESUMEN_PREQ.V1")]
    public partial class AL_PPN_PROF_WKIMsgDataRecord_TypeShape : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aL_PPN_PROFField;
        
        private string classField;
        
        public AL_PPN_PROF_WKIMsgDataRecord_TypeShape() {
            this.classField = "R";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string AL_PPN_PROF {
            get {
                return this.aL_PPN_PROFField;
            }
            set {
                this.aL_PPN_PROFField = value;
                this.RaisePropertyChanged("AL_PPN_PROF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Enterprise/Tools/schemas/AL_CONS_REQXMED_RESUMEN_PREQ.V1")]
    public partial class AL_CONS_REQXMED_RESUMEN_PREQ_TypeShape : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AL_PPN_PROF_WKIMsgDataRecord_TypeShape aL_PPN_PROF_WKIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AL_PPN_PROF_WKIMsgDataRecord_TypeShape AL_PPN_PROF_WKI {
            get {
                return this.aL_PPN_PROF_WKIField;
            }
            set {
                this.aL_PPN_PROF_WKIField = value;
                this.RaisePropertyChanged("AL_PPN_PROF_WKI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Enterprise/Tools/schemas/AL_CONS_REQXMED_RESUMEN_CREQ.V1")]
    public partial class AL_CONS_REQXMED_RESUMEN_CREQType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AL_CONS_REQXMED_RESUMEN_PREQ_TypeShape aL_CONS_REQXMED_RESUMEN_PREQField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AL_CONS_REQXMED_RESUMEN_PREQ_TypeShape AL_CONS_REQXMED_RESUMEN_PREQ {
            get {
                return this.aL_CONS_REQXMED_RESUMEN_PREQField;
            }
            set {
                this.aL_CONS_REQXMED_RESUMEN_PREQField = value;
                this.RaisePropertyChanged("AL_CONS_REQXMED_RESUMEN_PREQ");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Enterprise/Tools/schemas/AL_CONS_REQXMED_DETALLE_PRES.V1")]
    public partial class AL_REQCDDTL_WKIMsgDataRecord_TypeShape : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rC_SOURCEField;
        
        private string aL_RECEP_REQField;
        
        private string aL_ENTREGA_REQField;
        
        private string dESCR_SERVICIOField;
        
        private string aL_FLAG_URG_CASEField;
        
        private string aGEField;
        
        private System.DateTime aL_FECH_NAC_PField;
        
        private string aDDRESS_DESCRField;
        
        private System.DateTime aL_FECH_NAC_HField;
        
        private string aL_MEDICAMENTOField;
        
        private string aL_MILIGRAMOSField;
        
        private System.DateTime aL_DESDE_FECHAField;
        
        private System.DateTime aL_SOL_LIC_DESDEField;
        
        private string aL_FORM_REC_COMField;
        
        private string aL_RECETAField;
        
        private string aL_CANTIDADField;
        
        private System.DateTime aL_FECH_ULT_REGField;
        
        private string nOMBRE_MAMA_O_PAPAField;
        
        private string rUT_MAMA_O_PAPAField;
        
        private System.DateTime aL_FECH_ENTREGAField;
        
        private string classField;
        
        public AL_REQCDDTL_WKIMsgDataRecord_TypeShape() {
            this.classField = "R";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RC_SOURCE {
            get {
                return this.rC_SOURCEField;
            }
            set {
                this.rC_SOURCEField = value;
                this.RaisePropertyChanged("RC_SOURCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AL_RECEP_REQ {
            get {
                return this.aL_RECEP_REQField;
            }
            set {
                this.aL_RECEP_REQField = value;
                this.RaisePropertyChanged("AL_RECEP_REQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AL_ENTREGA_REQ {
            get {
                return this.aL_ENTREGA_REQField;
            }
            set {
                this.aL_ENTREGA_REQField = value;
                this.RaisePropertyChanged("AL_ENTREGA_REQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DESCR_SERVICIO {
            get {
                return this.dESCR_SERVICIOField;
            }
            set {
                this.dESCR_SERVICIOField = value;
                this.RaisePropertyChanged("DESCR_SERVICIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AL_FLAG_URG_CASE {
            get {
                return this.aL_FLAG_URG_CASEField;
            }
            set {
                this.aL_FLAG_URG_CASEField = value;
                this.RaisePropertyChanged("AL_FLAG_URG_CASE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string AGE {
            get {
                return this.aGEField;
            }
            set {
                this.aGEField = value;
                this.RaisePropertyChanged("AGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime AL_FECH_NAC_P {
            get {
                return this.aL_FECH_NAC_PField;
            }
            set {
                this.aL_FECH_NAC_PField = value;
                this.RaisePropertyChanged("AL_FECH_NAC_P");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ADDRESS_DESCR {
            get {
                return this.aDDRESS_DESCRField;
            }
            set {
                this.aDDRESS_DESCRField = value;
                this.RaisePropertyChanged("ADDRESS_DESCR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=8)]
        public System.DateTime AL_FECH_NAC_H {
            get {
                return this.aL_FECH_NAC_HField;
            }
            set {
                this.aL_FECH_NAC_HField = value;
                this.RaisePropertyChanged("AL_FECH_NAC_H");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string AL_MEDICAMENTO {
            get {
                return this.aL_MEDICAMENTOField;
            }
            set {
                this.aL_MEDICAMENTOField = value;
                this.RaisePropertyChanged("AL_MEDICAMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AL_MILIGRAMOS {
            get {
                return this.aL_MILIGRAMOSField;
            }
            set {
                this.aL_MILIGRAMOSField = value;
                this.RaisePropertyChanged("AL_MILIGRAMOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=11)]
        public System.DateTime AL_DESDE_FECHA {
            get {
                return this.aL_DESDE_FECHAField;
            }
            set {
                this.aL_DESDE_FECHAField = value;
                this.RaisePropertyChanged("AL_DESDE_FECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=12)]
        public System.DateTime AL_SOL_LIC_DESDE {
            get {
                return this.aL_SOL_LIC_DESDEField;
            }
            set {
                this.aL_SOL_LIC_DESDEField = value;
                this.RaisePropertyChanged("AL_SOL_LIC_DESDE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string AL_FORM_REC_COM {
            get {
                return this.aL_FORM_REC_COMField;
            }
            set {
                this.aL_FORM_REC_COMField = value;
                this.RaisePropertyChanged("AL_FORM_REC_COM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string AL_RECETA {
            get {
                return this.aL_RECETAField;
            }
            set {
                this.aL_RECETAField = value;
                this.RaisePropertyChanged("AL_RECETA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=15)]
        public string AL_CANTIDAD {
            get {
                return this.aL_CANTIDADField;
            }
            set {
                this.aL_CANTIDADField = value;
                this.RaisePropertyChanged("AL_CANTIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=16)]
        public System.DateTime AL_FECH_ULT_REG {
            get {
                return this.aL_FECH_ULT_REGField;
            }
            set {
                this.aL_FECH_ULT_REGField = value;
                this.RaisePropertyChanged("AL_FECH_ULT_REG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string NOMBRE_MAMA_O_PAPA {
            get {
                return this.nOMBRE_MAMA_O_PAPAField;
            }
            set {
                this.nOMBRE_MAMA_O_PAPAField = value;
                this.RaisePropertyChanged("NOMBRE_MAMA_O_PAPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string RUT_MAMA_O_PAPA {
            get {
                return this.rUT_MAMA_O_PAPAField;
            }
            set {
                this.rUT_MAMA_O_PAPAField = value;
                this.RaisePropertyChanged("RUT_MAMA_O_PAPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=19)]
        public System.DateTime AL_FECH_ENTREGA {
            get {
                return this.aL_FECH_ENTREGAField;
            }
            set {
                this.aL_FECH_ENTREGAField = value;
                this.RaisePropertyChanged("AL_FECH_ENTREGA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Enterprise/Tools/schemas/AL_CONS_REQXMED_DETALLE_PRES.V1")]
    public partial class AL_CONS_REQXMED_DETALLE_PRES_TypeShape : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AL_REQCDDTL_WKIMsgDataRecord_TypeShape aL_REQCDDTL_WKIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AL_REQCDDTL_WKIMsgDataRecord_TypeShape AL_REQCDDTL_WKI {
            get {
                return this.aL_REQCDDTL_WKIField;
            }
            set {
                this.aL_REQCDDTL_WKIField = value;
                this.RaisePropertyChanged("AL_REQCDDTL_WKI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AL_CONS_REQXMED_DETALLE_CREQV1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Enterprise/Tools/schemas/AL_CONS_REQXMED_DETALLE_CREQ.V1", Order=0)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CREQType AL_CONS_REQXMED_DETALLE_CREQ;
        
        public AL_CONS_REQXMED_DETALLE_CREQV1() {
        }
        
        public AL_CONS_REQXMED_DETALLE_CREQV1(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CREQType AL_CONS_REQXMED_DETALLE_CREQ) {
            this.AL_CONS_REQXMED_DETALLE_CREQ = AL_CONS_REQXMED_DETALLE_CREQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AL_CONS_REQXMED_DETALLE_CRESV1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Enterprise/Tools/schemas/AL_CONS_REQXMED_DETALLE_CRES.V1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AL_CONS_REQXMED_DETALLE_PRES", IsNullable=false)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_PRES_TypeShape[] AL_CONS_REQXMED_DETALLE_CRES;
        
        public AL_CONS_REQXMED_DETALLE_CRESV1() {
        }
        
        public AL_CONS_REQXMED_DETALLE_CRESV1(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_PRES_TypeShape[] AL_CONS_REQXMED_DETALLE_CRES) {
            this.AL_CONS_REQXMED_DETALLE_CRES = AL_CONS_REQXMED_DETALLE_CRES;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AL_CONS_REQXMED_RESUMEN_CREQV1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Enterprise/Tools/schemas/AL_CONS_REQXMED_RESUMEN_CREQ.V1", Order=0)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CREQType AL_CONS_REQXMED_RESUMEN_CREQ;
        
        public AL_CONS_REQXMED_RESUMEN_CREQV1() {
        }
        
        public AL_CONS_REQXMED_RESUMEN_CREQV1(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CREQType AL_CONS_REQXMED_RESUMEN_CREQ) {
            this.AL_CONS_REQXMED_RESUMEN_CREQ = AL_CONS_REQXMED_RESUMEN_CREQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AL_CONS_REQXMED_RESUMEN_CRESV1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Enterprise/Tools/schemas/AL_CONS_REQXMED_RESUMEN_CRES.V1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AL_CONS_REQXMED_RESUMEN_PRES", IsNullable=false)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_PRES_TypeShape[] AL_CONS_REQXMED_RESUMEN_CRES;
        
        public AL_CONS_REQXMED_RESUMEN_CRESV1() {
        }
        
        public AL_CONS_REQXMED_RESUMEN_CRESV1(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_PRES_TypeShape[] AL_CONS_REQXMED_RESUMEN_CRES) {
            this.AL_CONS_REQXMED_RESUMEN_CRES = AL_CONS_REQXMED_RESUMEN_CRES;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AL_INTEGRACION_NUCLEO_PortTypeChannel : Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_INTEGRACION_NUCLEO_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AL_INTEGRACION_NUCLEO_PortTypeClient : System.ServiceModel.ClientBase<Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_INTEGRACION_NUCLEO_PortType>, Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_INTEGRACION_NUCLEO_PortType {
        
        public AL_INTEGRACION_NUCLEO_PortTypeClient() {
        }
        
        public AL_INTEGRACION_NUCLEO_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AL_INTEGRACION_NUCLEO_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AL_INTEGRACION_NUCLEO_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AL_INTEGRACION_NUCLEO_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CRESV1 Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_INTEGRACION_NUCLEO_PortType.AL_CONS_REQXMED_DETALLE(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CREQV1 request) {
            return base.Channel.AL_CONS_REQXMED_DETALLE(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_PRES_TypeShape[] AL_CONS_REQXMED_DETALLE(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CREQType AL_CONS_REQXMED_DETALLE_CREQ) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CREQV1 inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CREQV1();
            inValue.AL_CONS_REQXMED_DETALLE_CREQ = AL_CONS_REQXMED_DETALLE_CREQ;
            Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CRESV1 retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_INTEGRACION_NUCLEO_PortType)(this)).AL_CONS_REQXMED_DETALLE(inValue);
            return retVal.AL_CONS_REQXMED_DETALLE_CRES;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CRESV1> Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_INTEGRACION_NUCLEO_PortType.AL_CONS_REQXMED_DETALLEAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CREQV1 request) {
            return base.Channel.AL_CONS_REQXMED_DETALLEAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CRESV1> AL_CONS_REQXMED_DETALLEAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CREQType AL_CONS_REQXMED_DETALLE_CREQ) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CREQV1 inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_DETALLE_CREQV1();
            inValue.AL_CONS_REQXMED_DETALLE_CREQ = AL_CONS_REQXMED_DETALLE_CREQ;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_INTEGRACION_NUCLEO_PortType)(this)).AL_CONS_REQXMED_DETALLEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CRESV1 Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_INTEGRACION_NUCLEO_PortType.AL_CONS_REQXMED_RESUMEN(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CREQV1 request) {
            return base.Channel.AL_CONS_REQXMED_RESUMEN(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_PRES_TypeShape[] AL_CONS_REQXMED_RESUMEN(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CREQType AL_CONS_REQXMED_RESUMEN_CREQ) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CREQV1 inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CREQV1();
            inValue.AL_CONS_REQXMED_RESUMEN_CREQ = AL_CONS_REQXMED_RESUMEN_CREQ;
            Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CRESV1 retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_INTEGRACION_NUCLEO_PortType)(this)).AL_CONS_REQXMED_RESUMEN(inValue);
            return retVal.AL_CONS_REQXMED_RESUMEN_CRES;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CRESV1> Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_INTEGRACION_NUCLEO_PortType.AL_CONS_REQXMED_RESUMENAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CREQV1 request) {
            return base.Channel.AL_CONS_REQXMED_RESUMENAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CRESV1> AL_CONS_REQXMED_RESUMENAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CREQType AL_CONS_REQXMED_RESUMEN_CREQ) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CREQV1 inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_CONS_REQXMED_RESUMEN_CREQV1();
            inValue.AL_CONS_REQXMED_RESUMEN_CREQ = AL_CONS_REQXMED_RESUMEN_CREQ;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsIntegracionCRM.AL_INTEGRACION_NUCLEO_PortType)(this)).AL_CONS_REQXMED_RESUMENAsync(inValue);
        }
    }
}
