//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alemana.Nucleo.Common
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alemana.Nucleo.Common.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del tipo de contador de Alemana no puede ser vacío o nulo.
        /// </summary>
        internal static string AlemanaCounterTypeNullOrEmpry {
            get {
                return ResourceManager.GetString("AlemanaCounterTypeNullOrEmpry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error cuando se intentaba procesar un evento de trace. El mensaje original que no se pudo almacenar en el log {0}..
        /// </summary>
        internal static string AsyncTraceError {
            get {
                return ResourceManager.GetString("AsyncTraceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseRepository: La cantidad de parámetros esperada por el comando [{0}] es diferente a la cantidad de parámetros suminstrada ({1} parametros recibidos)..
        /// </summary>
        internal static string BaseRepository_WrongNumberOfParams {
            get {
                return ResourceManager.GetString("BaseRepository_WrongNumberOfParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible obtener ni agregar al caché el elemento para la clave &apos;{0}&apos;..
        /// </summary>
        internal static string CacheAddOrGetItemFailed {
            get {
                return ResourceManager.GetString("CacheAddOrGetItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar la configuración de manejo de caché del archivo de configuración.
        /// </summary>
        internal static string CacheLoadError {
            get {
                return ResourceManager.GetString("CacheLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo crear un objeto de tipo LogEntry.
        /// </summary>
        internal static string CantCreateLogEntryObject {
            get {
                return ResourceManager.GetString("CantCreateLogEntryObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible mapear la propiedad {0} ya que la columna {1} no fue recibida desde la base de datos..
        /// </summary>
        internal static string CantMapPropertyColumnNotFound {
            get {
                return ResourceManager.GetString("CantMapPropertyColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La categoría {0} ya tiene un contador llamado {1}.
        /// </summary>
        internal static string CategoryAlreadyHasCounterName {
            get {
                return ResourceManager.GetString("CategoryAlreadyHasCounterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la categoría no puede ser vacío o nulo.
        /// </summary>
        internal static string CategoryNameNullOrEmpty {
            get {
                return ResourceManager.GetString("CategoryNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La categoría {0} ya existe.
        /// </summary>
        internal static string CounterCategoryAlreadyExists {
            get {
                return ResourceManager.GetString("CounterCategoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La categoría {0} no existe.
        /// </summary>
        internal static string CounterCategoryDoesntExist {
            get {
                return ResourceManager.GetString("CounterCategoryDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La instancia {0} ya existe en el contador {1}.
        /// </summary>
        internal static string CounterInstanceAlreadyExists {
            get {
                return ResourceManager.GetString("CounterInstanceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proveedor de acceso a base de datos no se encuentra configurado en el string de conexión. Verifique en la sección &lt;connectionStrings /&gt; que para la conexión {0} se encuentre configurado el atributo &apos;Provider&apos;.
        /// </summary>
        internal static string DbProviderIsNotConfigured {
            get {
                return ResourceManager.GetString("DbProviderIsNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseRepository.ctor: El mapper por defecto no puede ser null. Verifique el parámetro &apos;defaultMapper&apos;..
        /// </summary>
        internal static string DefaultMapperCannotBeNull {
            get {
                return ResourceManager.GetString("DefaultMapperCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la política no puede ser vacío.
        /// </summary>
        internal static string EmptyPolicyName {
            get {
                return ResourceManager.GetString("EmptyPolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo no puede ser vacío.
        /// </summary>
        internal static string EmptyType {
            get {
                return ResourceManager.GetString("EmptyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al intentar obtener la sección &quot;{0}&quot;del archivo de configuración.
        /// </summary>
        internal static string ErrorGettingConfigurationSection {
            get {
                return ResourceManager.GetString("ErrorGettingConfigurationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al intentar eliminar la categoría [{0}].
        /// </summary>
        internal static string ExceptionCounterCategoryDeletion {
            get {
                return ResourceManager.GetString("ExceptionCounterCategoryDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar la configuración de manejo de excepciones del archivo de configuración.
        /// </summary>
        internal static string ExceptionHandlingLoadError {
            get {
                return ResourceManager.GetString("ExceptionHandlingLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la política no existe entre las definidas en el archivo de configuración:.
        /// </summary>
        internal static string InexistentPolicyName {
            get {
                return ResourceManager.GetString("InexistentPolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al inicializar el módulo de instrumentación.
        /// </summary>
        internal static string InstrumentationInitializationError {
            get {
                return ResourceManager.GetString("InstrumentationInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se tienen suficientes permisos para crear la categoría de contadores: {0}.
        /// </summary>
        internal static string InsufficientPermissionsForCounterCategoryCreation {
            get {
                return ResourceManager.GetString("InsufficientPermissionsForCounterCategoryCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se tienen suficientes permisos para borra la categoría {0}.
        /// </summary>
        internal static string InsufficientPermissionsForCounterCategoryDeletion {
            get {
                return ResourceManager.GetString("InsufficientPermissionsForCounterCategoryDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se tienen suficientes permisos para leer los contadores.
        /// </summary>
        internal static string InsufficientPermissionsForCounterReading {
            get {
                return ResourceManager.GetString("InsufficientPermissionsForCounterReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La accion no es válida.
        /// </summary>
        internal static string InvalidAction {
            get {
                return ResourceManager.GetString("InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del tipo de de contador de Alemana {0} no es válido, los valores posibles son: {1}.
        /// </summary>
        internal static string InvalidAlemanaCounterType {
            get {
                return ResourceManager.GetString("InvalidAlemanaCounterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InvalidCacheType {
            get {
                return ResourceManager.GetString("InvalidCacheType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener un string de conexión válido para el nombre {0}. Verifique la seccion &lt;connectionStrings/&gt; del archivo de configuración de la aplicación..
        /// </summary>
        internal static string InvalidConnectionString {
            get {
                return ResourceManager.GetString("InvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del tipo de categoría de contadores de performance &quot;{0}&quot; no es válido, lo valores válidos son: {1}.
        /// </summary>
        internal static string InvalidCounterCategoryType {
            get {
                return ResourceManager.GetString("InvalidCounterCategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo del contador no es válido para esta operación.
        /// </summary>
        internal static string InvalidCounterForOperation {
            get {
                return ResourceManager.GetString("InvalidCounterForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible determinar el source destino. Debe especificar el TraceSource de destino en el atributo initializationData. Verifique la configuración de &lt;system.diagnostics /&gt;.
        /// </summary>
        internal static string InvalidTraceSource {
            get {
                return ResourceManager.GetString("InvalidTraceSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo crear el TraceSource con el nombre especificado :{0} . Verifique el nombre..
        /// </summary>
        internal static string InvalidTraceSourceName {
            get {
                return ResourceManager.GetString("InvalidTraceSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo no es válido: {0}.
        /// </summary>
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor no es válido: {0}.
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error - GUID:{0} . Mensaje: {1}. Stack Trace:{2}. {3}.
        /// </summary>
        internal static string NucleoCommonException {
            get {
                return ResourceManager.GetString("NucleoCommonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro no puede ser null: {0}.
        /// </summary>
        internal static string ParameterCanBeNull {
            get {
                return ResourceManager.GetString("ParameterCanBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerformanceCounterHelper: No es posible obtener el contador [{0}] ya que no existe la categoría [{0}] de Performance Counters..
        /// </summary>
        internal static string PerformanceCounterHelper_CategoryNotFound {
            get {
                return ResourceManager.GetString("PerformanceCounterHelper_CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerformanceCounterHelper: No se encontró el Performance Counter [{0}] en la categoría [{1}]..
        /// </summary>
        internal static string PerformanceCounterHelper_CounterNotFound {
            get {
                return ResourceManager.GetString("PerformanceCounterHelper_CounterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La política &quot;{0}&quot; no tiene un tipo asociado a: {1}.
        /// </summary>
        internal static string PolicyWithoutAssociatedType {
            get {
                return ResourceManager.GetString("PolicyWithoutAssociatedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReflectionHelper: La expresión lambda indicada debe apuntar a una propiedad de la clase..
        /// </summary>
        internal static string ReflectionHelper_BadLambdaProperty {
            get {
                return ResourceManager.GetString("ReflectionHelper_BadLambdaProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReflectionHelper: No es posible realizar un &apos;cast&apos; del tipo [{0}] al tipo [{1}]..
        /// </summary>
        internal static string ReflectionHelper_CantCastToType {
            get {
                return ResourceManager.GetString("ReflectionHelper_CantCastToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReflectionHelper: El tipo [{0}] no pudo ser instanciado..
        /// </summary>
        internal static string ReflectionHelper_CantCreateInstance {
            get {
                return ResourceManager.GetString("ReflectionHelper_CantCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReflectionHelper: El tipo [{0}] no fue encontrado..
        /// </summary>
        internal static string ReflectionHelper_TypeNotFound {
            get {
                return ResourceManager.GetString("ReflectionHelper_TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El recurso fue liberado.
        /// </summary>
        internal static string ResourceDisposed {
            get {
                return ResourceManager.GetString("ResourceDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible cargar la configuración del administrador de seguridad. Verifique la sección &lt;securtitySection/&gt;.
        /// </summary>
        internal static string SecurityManagerConfigError {
            get {
                return ResourceManager.GetString("SecurityManagerConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlRepository: No es posible asignar parámetros a un comando de tipo texto, solo a un stored procedure. El texto del comando recibido es [{0}]..
        /// </summary>
        internal static string SqlRepository_CantAssignParametersToTextCommand {
            get {
                return ResourceManager.GetString("SqlRepository_CantAssignParametersToTextCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo no hereda de System.Exception:.
        /// </summary>
        internal static string TypeDoesNotInheritsFromException {
            get {
                return ResourceManager.GetString("TypeDoesNotInheritsFromException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave &quot;{0}&quot; debe estar definida en el archivo de configuración y tener un valor asignado.
        /// </summary>
        internal static string UndefinedKeyOrInexistentValue {
            get {
                return ResourceManager.GetString("UndefinedKeyOrInexistentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se definieron las políticas de cache.
        /// </summary>
        internal static string UndefinedPolicies {
            get {
                return ResourceManager.GetString("UndefinedPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo debe ser un enumerado: {0}.
        /// </summary>
        internal static string ValueHasToBeEnum {
            get {
                return ResourceManager.GetString("ValueHasToBeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor no tiene un tipo base asociado: {0}.
        /// </summary>
        internal static string ValueWithoutAssociatedBaseType {
            get {
                return ResourceManager.GetString("ValueWithoutAssociatedBaseType", resourceCulture);
            }
        }
    }
}
