//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nucleo.alemana.cl/", ConfigurationName="WsIncidenciaModulos.WsincidenciamoduloWeb")]
    public interface WsincidenciamoduloWeb {
        
        // CODEGEN: El parámetro 'evpspDataFromBdSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspDataFromBdSelResponse evpspDataFromBdSel(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspDataFromBdSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspDataFromBdSelResponse> evpspDataFromBdSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspDataFromBdSelRequest request);
        
        // CODEGEN: El parámetro 'evpspIncModInsUpdResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModInsUpdResponse evpspIncModInsUpd(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModInsUpdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModInsUpdResponse> evpspIncModInsUpdAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModInsUpdRequest request);
        
        // CODEGEN: El parámetro 'evpspIncModSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModSelResponse evpspIncModSel(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModSelResponse> evpspIncModSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModSelRequest request);
        
        // CODEGEN: El parámetro 'evpspVarIncModInsResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModInsResponse evpspVarIncModIns(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModInsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModInsResponse> evpspVarIncModInsAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModInsRequest request);
        
        // CODEGEN: El parámetro 'evpspVarIncModSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModSelResponse evpspVarIncModSel(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModSelResponse> evpspVarIncModSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModSelRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EvpspDataFromBdSelResult : ProcedureResult {
        
        private string poDataField;
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string poData {
            get {
                return this.poDataField;
            }
            set {
                this.poDataField = value;
                this.RaisePropertyChanged("poData");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EvpspIncModInsUpdResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EvpspIncModSelResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EvpspDataFromBdSelResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EvpspVarIncModInsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EvpspVarIncModSelResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public abstract partial class ProcedureResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EvpspIncModSelTModuloVigente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aliasUsuarioField;
        
        private decimal consolidadoField;
        
        private bool consolidadoFieldSpecified;
        
        private decimal encuentroField;
        
        private bool encuentroFieldSpecified;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private decimal idAreaField;
        
        private bool idAreaFieldSpecified;
        
        private decimal idModuloField;
        
        private bool idModuloFieldSpecified;
        
        private decimal sesionCreadorIdField;
        
        private bool sesionCreadorIdFieldSpecified;
        
        private decimal vigenteField;
        
        private bool vigenteFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string aliasUsuario {
            get {
                return this.aliasUsuarioField;
            }
            set {
                this.aliasUsuarioField = value;
                this.RaisePropertyChanged("aliasUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal consolidado {
            get {
                return this.consolidadoField;
            }
            set {
                this.consolidadoField = value;
                this.RaisePropertyChanged("consolidado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool consolidadoSpecified {
            get {
                return this.consolidadoFieldSpecified;
            }
            set {
                this.consolidadoFieldSpecified = value;
                this.RaisePropertyChanged("consolidadoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal encuentro {
            get {
                return this.encuentroField;
            }
            set {
                this.encuentroField = value;
                this.RaisePropertyChanged("encuentro");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool encuentroSpecified {
            get {
                return this.encuentroFieldSpecified;
            }
            set {
                this.encuentroFieldSpecified = value;
                this.RaisePropertyChanged("encuentroSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal idArea {
            get {
                return this.idAreaField;
            }
            set {
                this.idAreaField = value;
                this.RaisePropertyChanged("idArea");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAreaSpecified {
            get {
                return this.idAreaFieldSpecified;
            }
            set {
                this.idAreaFieldSpecified = value;
                this.RaisePropertyChanged("idAreaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal idModulo {
            get {
                return this.idModuloField;
            }
            set {
                this.idModuloField = value;
                this.RaisePropertyChanged("idModulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idModuloSpecified {
            get {
                return this.idModuloFieldSpecified;
            }
            set {
                this.idModuloFieldSpecified = value;
                this.RaisePropertyChanged("idModuloSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal sesionCreadorId {
            get {
                return this.sesionCreadorIdField;
            }
            set {
                this.sesionCreadorIdField = value;
                this.RaisePropertyChanged("sesionCreadorId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sesionCreadorIdSpecified {
            get {
                return this.sesionCreadorIdFieldSpecified;
            }
            set {
                this.sesionCreadorIdFieldSpecified = value;
                this.RaisePropertyChanged("sesionCreadorIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal vigente {
            get {
                return this.vigenteField;
            }
            set {
                this.vigenteField = value;
                this.RaisePropertyChanged("vigente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vigenteSpecified {
            get {
                return this.vigenteFieldSpecified;
            }
            set {
                this.vigenteFieldSpecified = value;
                this.RaisePropertyChanged("vigenteSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EvpspVarIncModSelTVariableIncidenciaModulo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal columnaField;
        
        private bool columnaFieldSpecified;
        
        private string detalleValorField;
        
        private decimal filaField;
        
        private bool filaFieldSpecified;
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private decimal idAgrupadorField;
        
        private bool idAgrupadorFieldSpecified;
        
        private decimal idVariableField;
        
        private bool idVariableFieldSpecified;
        
        private string justificacionField;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal columna {
            get {
                return this.columnaField;
            }
            set {
                this.columnaField = value;
                this.RaisePropertyChanged("columna");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool columnaSpecified {
            get {
                return this.columnaFieldSpecified;
            }
            set {
                this.columnaFieldSpecified = value;
                this.RaisePropertyChanged("columnaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string detalleValor {
            get {
                return this.detalleValorField;
            }
            set {
                this.detalleValorField = value;
                this.RaisePropertyChanged("detalleValor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal fila {
            get {
                return this.filaField;
            }
            set {
                this.filaField = value;
                this.RaisePropertyChanged("fila");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool filaSpecified {
            get {
                return this.filaFieldSpecified;
            }
            set {
                this.filaFieldSpecified = value;
                this.RaisePropertyChanged("filaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal idAgrupador {
            get {
                return this.idAgrupadorField;
            }
            set {
                this.idAgrupadorField = value;
                this.RaisePropertyChanged("idAgrupador");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAgrupadorSpecified {
            get {
                return this.idAgrupadorFieldSpecified;
            }
            set {
                this.idAgrupadorFieldSpecified = value;
                this.RaisePropertyChanged("idAgrupadorSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal idVariable {
            get {
                return this.idVariableField;
            }
            set {
                this.idVariableField = value;
                this.RaisePropertyChanged("idVariable");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idVariableSpecified {
            get {
                return this.idVariableFieldSpecified;
            }
            set {
                this.idVariableFieldSpecified = value;
                this.RaisePropertyChanged("idVariableSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string justificacion {
            get {
                return this.justificacionField;
            }
            set {
                this.justificacionField = value;
                this.RaisePropertyChanged("justificacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EvpspIncModInsUpdResult : ProcedureResult {
        
        private decimal pioEncnuEncuentroIdField;
        
        private bool pioEncnuEncuentroIdFieldSpecified;
        
        private decimal pioEvpnuIncidenciaModuloIdField;
        
        private bool pioEvpnuIncidenciaModuloIdFieldSpecified;
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal pioEncnuEncuentroId {
            get {
                return this.pioEncnuEncuentroIdField;
            }
            set {
                this.pioEncnuEncuentroIdField = value;
                this.RaisePropertyChanged("pioEncnuEncuentroId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pioEncnuEncuentroIdSpecified {
            get {
                return this.pioEncnuEncuentroIdFieldSpecified;
            }
            set {
                this.pioEncnuEncuentroIdFieldSpecified = value;
                this.RaisePropertyChanged("pioEncnuEncuentroIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal pioEvpnuIncidenciaModuloId {
            get {
                return this.pioEvpnuIncidenciaModuloIdField;
            }
            set {
                this.pioEvpnuIncidenciaModuloIdField = value;
                this.RaisePropertyChanged("pioEvpnuIncidenciaModuloId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pioEvpnuIncidenciaModuloIdSpecified {
            get {
                return this.pioEvpnuIncidenciaModuloIdFieldSpecified;
            }
            set {
                this.pioEvpnuIncidenciaModuloIdFieldSpecified = value;
                this.RaisePropertyChanged("pioEvpnuIncidenciaModuloIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EvpspIncModSelResult : ProcedureResult {
        
        private EvpspIncModSelTModuloVigente[] moduloVigenteField;
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("moduloVigente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public EvpspIncModSelTModuloVigente[] moduloVigente {
            get {
                return this.moduloVigenteField;
            }
            set {
                this.moduloVigenteField = value;
                this.RaisePropertyChanged("moduloVigente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EvpspVarIncModInsResult : ProcedureResult {
        
        private decimal pioConnuEncuentroIdField;
        
        private bool pioConnuEncuentroIdFieldSpecified;
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        private decimal poVavnuVariableValorIdField;
        
        private bool poVavnuVariableValorIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal pioConnuEncuentroId {
            get {
                return this.pioConnuEncuentroIdField;
            }
            set {
                this.pioConnuEncuentroIdField = value;
                this.RaisePropertyChanged("pioConnuEncuentroId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pioConnuEncuentroIdSpecified {
            get {
                return this.pioConnuEncuentroIdFieldSpecified;
            }
            set {
                this.pioConnuEncuentroIdFieldSpecified = value;
                this.RaisePropertyChanged("pioConnuEncuentroIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal poVavnuVariableValorId {
            get {
                return this.poVavnuVariableValorIdField;
            }
            set {
                this.poVavnuVariableValorIdField = value;
                this.RaisePropertyChanged("poVavnuVariableValorId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poVavnuVariableValorIdSpecified {
            get {
                return this.poVavnuVariableValorIdFieldSpecified;
            }
            set {
                this.poVavnuVariableValorIdFieldSpecified = value;
                this.RaisePropertyChanged("poVavnuVariableValorIdSpecified");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EvpspVarIncModSelResult : ProcedureResult {
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        private EvpspVarIncModSelTVariableIncidenciaModulo[] variableIncidenciaModuloField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("variableIncidenciaModulo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public EvpspVarIncModSelTVariableIncidenciaModulo[] variableIncidenciaModulo {
            get {
                return this.variableIncidenciaModuloField;
            }
            set {
                this.variableIncidenciaModuloField = value;
                this.RaisePropertyChanged("variableIncidenciaModulo");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="evpspDataFromBdSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class evpspDataFromBdSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piSesnuSesionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piTipoCampo;
        
        public evpspDataFromBdSelRequest() {
        }
        
        public evpspDataFromBdSelRequest(decimal piSesnuSesionId, decimal piTipoCampo) {
            this.piSesnuSesionId = piSesnuSesionId;
            this.piTipoCampo = piTipoCampo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="evpspDataFromBdSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class evpspDataFromBdSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspDataFromBdSelResult evpspDataFromBdSelResult;
        
        public evpspDataFromBdSelResponse() {
        }
        
        public evpspDataFromBdSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspDataFromBdSelResult evpspDataFromBdSelResult) {
            this.evpspDataFromBdSelResult = evpspDataFromBdSelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="evpspIncModInsUpd", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class evpspIncModInsUpdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal pioEvpnuIncidenciaModuloId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piMdlnuModuloId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piFicnuFichaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piArenuAreaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEvpnuConsolidado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEvpnuVigente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEvpnuSessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEpinuEpisodioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEvpdaFecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEvpnuEliminarValores;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal pioEncnuEncuentroId;
        
        public evpspIncModInsUpdRequest() {
        }
        
        public evpspIncModInsUpdRequest(decimal pioEvpnuIncidenciaModuloId, decimal piMdlnuModuloId, decimal piFicnuFichaId, decimal piArenuAreaId, decimal piEvpnuConsolidado, decimal piEvpnuVigente, decimal piEvpnuSessionId, decimal piEpinuEpisodioId, System.DateTime piEvpdaFecha, decimal piEvpnuEliminarValores, decimal pioEncnuEncuentroId) {
            this.pioEvpnuIncidenciaModuloId = pioEvpnuIncidenciaModuloId;
            this.piMdlnuModuloId = piMdlnuModuloId;
            this.piFicnuFichaId = piFicnuFichaId;
            this.piArenuAreaId = piArenuAreaId;
            this.piEvpnuConsolidado = piEvpnuConsolidado;
            this.piEvpnuVigente = piEvpnuVigente;
            this.piEvpnuSessionId = piEvpnuSessionId;
            this.piEpinuEpisodioId = piEpinuEpisodioId;
            this.piEvpdaFecha = piEvpdaFecha;
            this.piEvpnuEliminarValores = piEvpnuEliminarValores;
            this.pioEncnuEncuentroId = pioEncnuEncuentroId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="evpspIncModInsUpdResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class evpspIncModInsUpdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspIncModInsUpdResult evpspIncModInsUpdResult;
        
        public evpspIncModInsUpdResponse() {
        }
        
        public evpspIncModInsUpdResponse(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspIncModInsUpdResult evpspIncModInsUpdResult) {
            this.evpspIncModInsUpdResult = evpspIncModInsUpdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="evpspIncModSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class evpspIncModSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piPtlnuPltId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piFicnuFichaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEncnuEncuentroId;
        
        public evpspIncModSelRequest() {
        }
        
        public evpspIncModSelRequest(decimal piPtlnuPltId, decimal piFicnuFichaId, decimal piEncnuEncuentroId) {
            this.piPtlnuPltId = piPtlnuPltId;
            this.piFicnuFichaId = piFicnuFichaId;
            this.piEncnuEncuentroId = piEncnuEncuentroId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="evpspIncModSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class evpspIncModSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspIncModSelResult evpspIncModSelResult;
        
        public evpspIncModSelResponse() {
        }
        
        public evpspIncModSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspIncModSelResult evpspIncModSelResult) {
            this.evpspIncModSelResult = evpspIncModSelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="evpspVarIncModIns", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class evpspVarIncModInsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEvpnuIncidenciaModuloId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piVarnuVariableId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piVavnuAgrupadorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piVavvaValor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piUsuarioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piFecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piVarnuFila;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piVarnuColumna;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piVavvaJustificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piVavvaDetalleValor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piSessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piFicnuFichaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEpsnuEpisodioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal pioConnuEncuentroId;
        
        public evpspVarIncModInsRequest() {
        }
        
        public evpspVarIncModInsRequest(decimal piEvpnuIncidenciaModuloId, decimal piVarnuVariableId, decimal piVavnuAgrupadorId, string piVavvaValor, decimal piUsuarioId, System.DateTime piFecha, decimal piVarnuFila, decimal piVarnuColumna, string piVavvaJustificacion, string piVavvaDetalleValor, decimal piSessionId, decimal piFicnuFichaId, decimal piEpsnuEpisodioId, decimal pioConnuEncuentroId) {
            this.piEvpnuIncidenciaModuloId = piEvpnuIncidenciaModuloId;
            this.piVarnuVariableId = piVarnuVariableId;
            this.piVavnuAgrupadorId = piVavnuAgrupadorId;
            this.piVavvaValor = piVavvaValor;
            this.piUsuarioId = piUsuarioId;
            this.piFecha = piFecha;
            this.piVarnuFila = piVarnuFila;
            this.piVarnuColumna = piVarnuColumna;
            this.piVavvaJustificacion = piVavvaJustificacion;
            this.piVavvaDetalleValor = piVavvaDetalleValor;
            this.piSessionId = piSessionId;
            this.piFicnuFichaId = piFicnuFichaId;
            this.piEpsnuEpisodioId = piEpsnuEpisodioId;
            this.pioConnuEncuentroId = pioConnuEncuentroId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="evpspVarIncModInsResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class evpspVarIncModInsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspVarIncModInsResult evpspVarIncModInsResult;
        
        public evpspVarIncModInsResponse() {
        }
        
        public evpspVarIncModInsResponse(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspVarIncModInsResult evpspVarIncModInsResult) {
            this.evpspVarIncModInsResult = evpspVarIncModInsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="evpspVarIncModSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class evpspVarIncModSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEvptmIncModId;
        
        public evpspVarIncModSelRequest() {
        }
        
        public evpspVarIncModSelRequest(decimal piEvptmIncModId) {
            this.piEvptmIncModId = piEvptmIncModId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="evpspVarIncModSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class evpspVarIncModSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspVarIncModSelResult evpspVarIncModSelResult;
        
        public evpspVarIncModSelResponse() {
        }
        
        public evpspVarIncModSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspVarIncModSelResult evpspVarIncModSelResult) {
            this.evpspVarIncModSelResult = evpspVarIncModSelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsincidenciamoduloWebChannel : Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsincidenciamoduloWebClient : System.ServiceModel.ClientBase<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb>, Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb {
        
        public WsincidenciamoduloWebClient() {
        }
        
        public WsincidenciamoduloWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsincidenciamoduloWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsincidenciamoduloWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsincidenciamoduloWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspDataFromBdSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb.evpspDataFromBdSel(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspDataFromBdSelRequest request) {
            return base.Channel.evpspDataFromBdSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspDataFromBdSelResult evpspDataFromBdSel(decimal piSesnuSesionId, decimal piTipoCampo) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspDataFromBdSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspDataFromBdSelRequest();
            inValue.piSesnuSesionId = piSesnuSesionId;
            inValue.piTipoCampo = piTipoCampo;
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspDataFromBdSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb)(this)).evpspDataFromBdSel(inValue);
            return retVal.evpspDataFromBdSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspDataFromBdSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb.evpspDataFromBdSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspDataFromBdSelRequest request) {
            return base.Channel.evpspDataFromBdSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspDataFromBdSelResponse> evpspDataFromBdSelAsync(decimal piSesnuSesionId, decimal piTipoCampo) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspDataFromBdSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspDataFromBdSelRequest();
            inValue.piSesnuSesionId = piSesnuSesionId;
            inValue.piTipoCampo = piTipoCampo;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb)(this)).evpspDataFromBdSelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModInsUpdResponse Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb.evpspIncModInsUpd(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModInsUpdRequest request) {
            return base.Channel.evpspIncModInsUpd(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspIncModInsUpdResult evpspIncModInsUpd(decimal pioEvpnuIncidenciaModuloId, decimal piMdlnuModuloId, decimal piFicnuFichaId, decimal piArenuAreaId, decimal piEvpnuConsolidado, decimal piEvpnuVigente, decimal piEvpnuSessionId, decimal piEpinuEpisodioId, System.DateTime piEvpdaFecha, decimal piEvpnuEliminarValores, decimal pioEncnuEncuentroId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModInsUpdRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModInsUpdRequest();
            inValue.pioEvpnuIncidenciaModuloId = pioEvpnuIncidenciaModuloId;
            inValue.piMdlnuModuloId = piMdlnuModuloId;
            inValue.piFicnuFichaId = piFicnuFichaId;
            inValue.piArenuAreaId = piArenuAreaId;
            inValue.piEvpnuConsolidado = piEvpnuConsolidado;
            inValue.piEvpnuVigente = piEvpnuVigente;
            inValue.piEvpnuSessionId = piEvpnuSessionId;
            inValue.piEpinuEpisodioId = piEpinuEpisodioId;
            inValue.piEvpdaFecha = piEvpdaFecha;
            inValue.piEvpnuEliminarValores = piEvpnuEliminarValores;
            inValue.pioEncnuEncuentroId = pioEncnuEncuentroId;
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModInsUpdResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb)(this)).evpspIncModInsUpd(inValue);
            return retVal.evpspIncModInsUpdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModInsUpdResponse> Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb.evpspIncModInsUpdAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModInsUpdRequest request) {
            return base.Channel.evpspIncModInsUpdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModInsUpdResponse> evpspIncModInsUpdAsync(decimal pioEvpnuIncidenciaModuloId, decimal piMdlnuModuloId, decimal piFicnuFichaId, decimal piArenuAreaId, decimal piEvpnuConsolidado, decimal piEvpnuVigente, decimal piEvpnuSessionId, decimal piEpinuEpisodioId, System.DateTime piEvpdaFecha, decimal piEvpnuEliminarValores, decimal pioEncnuEncuentroId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModInsUpdRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModInsUpdRequest();
            inValue.pioEvpnuIncidenciaModuloId = pioEvpnuIncidenciaModuloId;
            inValue.piMdlnuModuloId = piMdlnuModuloId;
            inValue.piFicnuFichaId = piFicnuFichaId;
            inValue.piArenuAreaId = piArenuAreaId;
            inValue.piEvpnuConsolidado = piEvpnuConsolidado;
            inValue.piEvpnuVigente = piEvpnuVigente;
            inValue.piEvpnuSessionId = piEvpnuSessionId;
            inValue.piEpinuEpisodioId = piEpinuEpisodioId;
            inValue.piEvpdaFecha = piEvpdaFecha;
            inValue.piEvpnuEliminarValores = piEvpnuEliminarValores;
            inValue.pioEncnuEncuentroId = pioEncnuEncuentroId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb)(this)).evpspIncModInsUpdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb.evpspIncModSel(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModSelRequest request) {
            return base.Channel.evpspIncModSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspIncModSelResult evpspIncModSel(decimal piPtlnuPltId, decimal piFicnuFichaId, decimal piEncnuEncuentroId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModSelRequest();
            inValue.piPtlnuPltId = piPtlnuPltId;
            inValue.piFicnuFichaId = piFicnuFichaId;
            inValue.piEncnuEncuentroId = piEncnuEncuentroId;
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb)(this)).evpspIncModSel(inValue);
            return retVal.evpspIncModSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb.evpspIncModSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModSelRequest request) {
            return base.Channel.evpspIncModSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModSelResponse> evpspIncModSelAsync(decimal piPtlnuPltId, decimal piFicnuFichaId, decimal piEncnuEncuentroId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspIncModSelRequest();
            inValue.piPtlnuPltId = piPtlnuPltId;
            inValue.piFicnuFichaId = piFicnuFichaId;
            inValue.piEncnuEncuentroId = piEncnuEncuentroId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb)(this)).evpspIncModSelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModInsResponse Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb.evpspVarIncModIns(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModInsRequest request) {
            return base.Channel.evpspVarIncModIns(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspVarIncModInsResult evpspVarIncModIns(decimal piEvpnuIncidenciaModuloId, decimal piVarnuVariableId, decimal piVavnuAgrupadorId, string piVavvaValor, decimal piUsuarioId, System.DateTime piFecha, decimal piVarnuFila, decimal piVarnuColumna, string piVavvaJustificacion, string piVavvaDetalleValor, decimal piSessionId, decimal piFicnuFichaId, decimal piEpsnuEpisodioId, decimal pioConnuEncuentroId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModInsRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModInsRequest();
            inValue.piEvpnuIncidenciaModuloId = piEvpnuIncidenciaModuloId;
            inValue.piVarnuVariableId = piVarnuVariableId;
            inValue.piVavnuAgrupadorId = piVavnuAgrupadorId;
            inValue.piVavvaValor = piVavvaValor;
            inValue.piUsuarioId = piUsuarioId;
            inValue.piFecha = piFecha;
            inValue.piVarnuFila = piVarnuFila;
            inValue.piVarnuColumna = piVarnuColumna;
            inValue.piVavvaJustificacion = piVavvaJustificacion;
            inValue.piVavvaDetalleValor = piVavvaDetalleValor;
            inValue.piSessionId = piSessionId;
            inValue.piFicnuFichaId = piFicnuFichaId;
            inValue.piEpsnuEpisodioId = piEpsnuEpisodioId;
            inValue.pioConnuEncuentroId = pioConnuEncuentroId;
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModInsResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb)(this)).evpspVarIncModIns(inValue);
            return retVal.evpspVarIncModInsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModInsResponse> Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb.evpspVarIncModInsAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModInsRequest request) {
            return base.Channel.evpspVarIncModInsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModInsResponse> evpspVarIncModInsAsync(decimal piEvpnuIncidenciaModuloId, decimal piVarnuVariableId, decimal piVavnuAgrupadorId, string piVavvaValor, decimal piUsuarioId, System.DateTime piFecha, decimal piVarnuFila, decimal piVarnuColumna, string piVavvaJustificacion, string piVavvaDetalleValor, decimal piSessionId, decimal piFicnuFichaId, decimal piEpsnuEpisodioId, decimal pioConnuEncuentroId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModInsRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModInsRequest();
            inValue.piEvpnuIncidenciaModuloId = piEvpnuIncidenciaModuloId;
            inValue.piVarnuVariableId = piVarnuVariableId;
            inValue.piVavnuAgrupadorId = piVavnuAgrupadorId;
            inValue.piVavvaValor = piVavvaValor;
            inValue.piUsuarioId = piUsuarioId;
            inValue.piFecha = piFecha;
            inValue.piVarnuFila = piVarnuFila;
            inValue.piVarnuColumna = piVarnuColumna;
            inValue.piVavvaJustificacion = piVavvaJustificacion;
            inValue.piVavvaDetalleValor = piVavvaDetalleValor;
            inValue.piSessionId = piSessionId;
            inValue.piFicnuFichaId = piFicnuFichaId;
            inValue.piEpsnuEpisodioId = piEpsnuEpisodioId;
            inValue.pioConnuEncuentroId = pioConnuEncuentroId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb)(this)).evpspVarIncModInsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb.evpspVarIncModSel(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModSelRequest request) {
            return base.Channel.evpspVarIncModSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.EvpspVarIncModSelResult evpspVarIncModSel(decimal piEvptmIncModId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModSelRequest();
            inValue.piEvptmIncModId = piEvptmIncModId;
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb)(this)).evpspVarIncModSel(inValue);
            return retVal.evpspVarIncModSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb.evpspVarIncModSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModSelRequest request) {
            return base.Channel.evpspVarIncModSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModSelResponse> evpspVarIncModSelAsync(decimal piEvptmIncModId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.evpspVarIncModSelRequest();
            inValue.piEvptmIncModId = piEvptmIncModId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsIncidenciaModulos.WsincidenciamoduloWeb)(this)).evpspVarIncModSelAsync(inValue);
        }
    }
}
