//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nucleo.alemana.cl/", ConfigurationName="WsPlantilla.WsplantillaestadisticaWeb")]
    public interface WsplantillaestadisticaWeb {
        
        // CODEGEN: El parámetro 'estspIncsmoduloPacienteSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsmoduloPacienteSelResponse estspIncsmoduloPacienteSel(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsmoduloPacienteSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsmoduloPacienteSelResponse> estspIncsmoduloPacienteSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsmoduloPacienteSelRequest request);
        
        // CODEGEN: El parámetro 'estspIncsvariableModuloSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsvariableModuloSelResponse estspIncsvariableModuloSel(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsvariableModuloSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsvariableModuloSelResponse> estspIncsvariableModuloSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsvariableModuloSelRequest request);
        
        // CODEGEN: El parámetro 'estspPacientesPlantillaSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPacientesPlantillaSelResponse estspPacientesPlantillaSel(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPacientesPlantillaSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPacientesPlantillaSelResponse> estspPacientesPlantillaSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPacientesPlantillaSelRequest request);
        
        // CODEGEN: El parámetro 'estspPlantillasSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPlantillasSelResponse estspPlantillasSel(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPlantillasSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPlantillasSelResponse> estspPlantillasSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPlantillasSelRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspIncsmoduloPacienteSelResult : ProcedureResult {
        
        private EstspIncsmoduloPacienteSelTIncidencias[] incidenciasField;
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("incidencias", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public EstspIncsmoduloPacienteSelTIncidencias[] incidencias {
            get {
                return this.incidenciasField;
            }
            set {
                this.incidenciasField = value;
                this.RaisePropertyChanged("incidencias");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspIncsmoduloPacienteSelTIncidencias : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal codigoField;
        
        private bool codigoFieldSpecified;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspPlantillasSelTPlantillas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspPacientesPlantillaSelTPacientes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private decimal pacienteidField;
        
        private bool pacienteidFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal pacienteid {
            get {
                return this.pacienteidField;
            }
            set {
                this.pacienteidField = value;
                this.RaisePropertyChanged("pacienteid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pacienteidSpecified {
            get {
                return this.pacienteidFieldSpecified;
            }
            set {
                this.pacienteidFieldSpecified = value;
                this.RaisePropertyChanged("pacienteidSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspIncsvariableModuloSelTIncidencias : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal codigoField;
        
        private bool codigoFieldSpecified;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstspPlantillasSelResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstspPacientesPlantillaSelResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstspIncsmoduloPacienteSelResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstspIncsvariableModuloSelResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public abstract partial class ProcedureResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspPlantillasSelResult : ProcedureResult {
        
        private EstspPlantillasSelTPlantillas[] plantillasField;
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("plantillas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public EstspPlantillasSelTPlantillas[] plantillas {
            get {
                return this.plantillasField;
            }
            set {
                this.plantillasField = value;
                this.RaisePropertyChanged("plantillas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspPacientesPlantillaSelResult : ProcedureResult {
        
        private EstspPacientesPlantillaSelTPacientes[] pacientesField;
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("pacientes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public EstspPacientesPlantillaSelTPacientes[] pacientes {
            get {
                return this.pacientesField;
            }
            set {
                this.pacientesField = value;
                this.RaisePropertyChanged("pacientes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspIncsvariableModuloSelResult : ProcedureResult {
        
        private EstspIncsvariableModuloSelTIncidencias[] incidenciasField;
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("incidencias", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public EstspIncsvariableModuloSelTIncidencias[] incidencias {
            get {
                return this.incidenciasField;
            }
            set {
                this.incidenciasField = value;
                this.RaisePropertyChanged("incidencias");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspIncsmoduloPacienteSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspIncsmoduloPacienteSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEstnuPlantillaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEstnuPacienteId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstUsuarios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstAreas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechainicioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechafinId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEpsdtTipofechaId;
        
        public estspIncsmoduloPacienteSelRequest() {
        }
        
        public estspIncsmoduloPacienteSelRequest(decimal piEstnuPlantillaId, decimal piEstnuPacienteId, string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId, decimal piEpsdtTipofechaId) {
            this.piEstnuPlantillaId = piEstnuPlantillaId;
            this.piEstnuPacienteId = piEstnuPacienteId;
            this.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            this.piEpsvaLstAreas = piEpsvaLstAreas;
            this.piEpsdtFechainicioId = piEpsdtFechainicioId;
            this.piEpsdtFechafinId = piEpsdtFechafinId;
            this.piEpsdtTipofechaId = piEpsdtTipofechaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspIncsmoduloPacienteSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspIncsmoduloPacienteSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.EstspIncsmoduloPacienteSelResult estspIncsmoduloPacienteSelResult;
        
        public estspIncsmoduloPacienteSelResponse() {
        }
        
        public estspIncsmoduloPacienteSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.EstspIncsmoduloPacienteSelResult estspIncsmoduloPacienteSelResult) {
            this.estspIncsmoduloPacienteSelResult = estspIncsmoduloPacienteSelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspIncsvariableModuloSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspIncsvariableModuloSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEstnuIncmouloId;
        
        public estspIncsvariableModuloSelRequest() {
        }
        
        public estspIncsvariableModuloSelRequest(decimal piEstnuIncmouloId) {
            this.piEstnuIncmouloId = piEstnuIncmouloId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspIncsvariableModuloSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspIncsvariableModuloSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.EstspIncsvariableModuloSelResult estspIncsvariableModuloSelResult;
        
        public estspIncsvariableModuloSelResponse() {
        }
        
        public estspIncsvariableModuloSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.EstspIncsvariableModuloSelResult estspIncsvariableModuloSelResult) {
            this.estspIncsvariableModuloSelResult = estspIncsvariableModuloSelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspPacientesPlantillaSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspPacientesPlantillaSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEstnuPlantillaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstUsuarios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstAreas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechainicioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechafinId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEpsdtTipofechaId;
        
        public estspPacientesPlantillaSelRequest() {
        }
        
        public estspPacientesPlantillaSelRequest(decimal piEstnuPlantillaId, string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId, decimal piEpsdtTipofechaId) {
            this.piEstnuPlantillaId = piEstnuPlantillaId;
            this.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            this.piEpsvaLstAreas = piEpsvaLstAreas;
            this.piEpsdtFechainicioId = piEpsdtFechainicioId;
            this.piEpsdtFechafinId = piEpsdtFechafinId;
            this.piEpsdtTipofechaId = piEpsdtTipofechaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspPacientesPlantillaSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspPacientesPlantillaSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.EstspPacientesPlantillaSelResult estspPacientesPlantillaSelResult;
        
        public estspPacientesPlantillaSelResponse() {
        }
        
        public estspPacientesPlantillaSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.EstspPacientesPlantillaSelResult estspPacientesPlantillaSelResult) {
            this.estspPacientesPlantillaSelResult = estspPacientesPlantillaSelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspPlantillasSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspPlantillasSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstUsuarios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstAreas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechainicioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechafinId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEpsdtTipofechaId;
        
        public estspPlantillasSelRequest() {
        }
        
        public estspPlantillasSelRequest(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId, decimal piEpsdtTipofechaId) {
            this.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            this.piEpsvaLstAreas = piEpsvaLstAreas;
            this.piEpsdtFechainicioId = piEpsdtFechainicioId;
            this.piEpsdtFechafinId = piEpsdtFechafinId;
            this.piEpsdtTipofechaId = piEpsdtTipofechaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspPlantillasSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspPlantillasSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.EstspPlantillasSelResult estspPlantillasSelResult;
        
        public estspPlantillasSelResponse() {
        }
        
        public estspPlantillasSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.EstspPlantillasSelResult estspPlantillasSelResult) {
            this.estspPlantillasSelResult = estspPlantillasSelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsplantillaestadisticaWebChannel : Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsplantillaestadisticaWebClient : System.ServiceModel.ClientBase<Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb>, Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb {
        
        public WsplantillaestadisticaWebClient() {
        }
        
        public WsplantillaestadisticaWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsplantillaestadisticaWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsplantillaestadisticaWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsplantillaestadisticaWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsmoduloPacienteSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb.estspIncsmoduloPacienteSel(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsmoduloPacienteSelRequest request) {
            return base.Channel.estspIncsmoduloPacienteSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.EstspIncsmoduloPacienteSelResult estspIncsmoduloPacienteSel(decimal piEstnuPlantillaId, decimal piEstnuPacienteId, string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId, decimal piEpsdtTipofechaId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsmoduloPacienteSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsmoduloPacienteSelRequest();
            inValue.piEstnuPlantillaId = piEstnuPlantillaId;
            inValue.piEstnuPacienteId = piEstnuPacienteId;
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            inValue.piEpsdtTipofechaId = piEpsdtTipofechaId;
            Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsmoduloPacienteSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb)(this)).estspIncsmoduloPacienteSel(inValue);
            return retVal.estspIncsmoduloPacienteSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsmoduloPacienteSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb.estspIncsmoduloPacienteSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsmoduloPacienteSelRequest request) {
            return base.Channel.estspIncsmoduloPacienteSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsmoduloPacienteSelResponse> estspIncsmoduloPacienteSelAsync(decimal piEstnuPlantillaId, decimal piEstnuPacienteId, string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId, decimal piEpsdtTipofechaId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsmoduloPacienteSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsmoduloPacienteSelRequest();
            inValue.piEstnuPlantillaId = piEstnuPlantillaId;
            inValue.piEstnuPacienteId = piEstnuPacienteId;
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            inValue.piEpsdtTipofechaId = piEpsdtTipofechaId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb)(this)).estspIncsmoduloPacienteSelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsvariableModuloSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb.estspIncsvariableModuloSel(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsvariableModuloSelRequest request) {
            return base.Channel.estspIncsvariableModuloSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.EstspIncsvariableModuloSelResult estspIncsvariableModuloSel(decimal piEstnuIncmouloId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsvariableModuloSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsvariableModuloSelRequest();
            inValue.piEstnuIncmouloId = piEstnuIncmouloId;
            Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsvariableModuloSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb)(this)).estspIncsvariableModuloSel(inValue);
            return retVal.estspIncsvariableModuloSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsvariableModuloSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb.estspIncsvariableModuloSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsvariableModuloSelRequest request) {
            return base.Channel.estspIncsvariableModuloSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsvariableModuloSelResponse> estspIncsvariableModuloSelAsync(decimal piEstnuIncmouloId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsvariableModuloSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspIncsvariableModuloSelRequest();
            inValue.piEstnuIncmouloId = piEstnuIncmouloId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb)(this)).estspIncsvariableModuloSelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPacientesPlantillaSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb.estspPacientesPlantillaSel(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPacientesPlantillaSelRequest request) {
            return base.Channel.estspPacientesPlantillaSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.EstspPacientesPlantillaSelResult estspPacientesPlantillaSel(decimal piEstnuPlantillaId, string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId, decimal piEpsdtTipofechaId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPacientesPlantillaSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPacientesPlantillaSelRequest();
            inValue.piEstnuPlantillaId = piEstnuPlantillaId;
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            inValue.piEpsdtTipofechaId = piEpsdtTipofechaId;
            Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPacientesPlantillaSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb)(this)).estspPacientesPlantillaSel(inValue);
            return retVal.estspPacientesPlantillaSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPacientesPlantillaSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb.estspPacientesPlantillaSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPacientesPlantillaSelRequest request) {
            return base.Channel.estspPacientesPlantillaSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPacientesPlantillaSelResponse> estspPacientesPlantillaSelAsync(decimal piEstnuPlantillaId, string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId, decimal piEpsdtTipofechaId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPacientesPlantillaSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPacientesPlantillaSelRequest();
            inValue.piEstnuPlantillaId = piEstnuPlantillaId;
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            inValue.piEpsdtTipofechaId = piEpsdtTipofechaId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb)(this)).estspPacientesPlantillaSelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPlantillasSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb.estspPlantillasSel(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPlantillasSelRequest request) {
            return base.Channel.estspPlantillasSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.EstspPlantillasSelResult estspPlantillasSel(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId, decimal piEpsdtTipofechaId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPlantillasSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPlantillasSelRequest();
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            inValue.piEpsdtTipofechaId = piEpsdtTipofechaId;
            Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPlantillasSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb)(this)).estspPlantillasSel(inValue);
            return retVal.estspPlantillasSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPlantillasSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb.estspPlantillasSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPlantillasSelRequest request) {
            return base.Channel.estspPlantillasSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPlantillasSelResponse> estspPlantillasSelAsync(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId, decimal piEpsdtTipofechaId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPlantillasSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.estspPlantillasSelRequest();
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            inValue.piEpsdtTipofechaId = piEpsdtTipofechaId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsPlantilla.WsplantillaestadisticaWeb)(this)).estspPlantillasSelAsync(inValue);
        }
    }
}
