//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alemana.Nucleo.Estadisticas.Servicio.WsFiltros {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nucleo.alemana.cl/", ConfigurationName="WsFiltros.WsfiltrosestadisticasWeb")]
    public interface WsfiltrosestadisticasWeb {
        
        // CODEGEN: El parámetro 'estspAreaSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspAreaSelResponse estspAreaSel(Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspAreaSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspAreaSelResponse> estspAreaSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspAreaSelRequest request);
        
        // CODEGEN: El parámetro 'estspProfesionalSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspProfesionalSelResponse estspProfesionalSel(Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspProfesionalSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspProfesionalSelResponse> estspProfesionalSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspProfesionalSelRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspAreaSelResult : ProcedureResult {
        
        private EstspAreaSelTAreas[] areasField;
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("areas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public EstspAreaSelTAreas[] areas {
            get {
                return this.areasField;
            }
            set {
                this.areasField = value;
                this.RaisePropertyChanged("areas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspAreaSelTAreas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspProfesionalSelTProfesionales : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidomaternoField;
        
        private string apellidopaternoField;
        
        private string nombresField;
        
        private decimal personaidField;
        
        private bool personaidFieldSpecified;
        
        private decimal usuarioidField;
        
        private bool usuarioidFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidomaterno {
            get {
                return this.apellidomaternoField;
            }
            set {
                this.apellidomaternoField = value;
                this.RaisePropertyChanged("apellidomaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidopaterno {
            get {
                return this.apellidopaternoField;
            }
            set {
                this.apellidopaternoField = value;
                this.RaisePropertyChanged("apellidopaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal personaid {
            get {
                return this.personaidField;
            }
            set {
                this.personaidField = value;
                this.RaisePropertyChanged("personaid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personaidSpecified {
            get {
                return this.personaidFieldSpecified;
            }
            set {
                this.personaidFieldSpecified = value;
                this.RaisePropertyChanged("personaidSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal usuarioid {
            get {
                return this.usuarioidField;
            }
            set {
                this.usuarioidField = value;
                this.RaisePropertyChanged("usuarioid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioidSpecified {
            get {
                return this.usuarioidFieldSpecified;
            }
            set {
                this.usuarioidFieldSpecified = value;
                this.RaisePropertyChanged("usuarioidSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstspProfesionalSelResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstspAreaSelResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public abstract partial class ProcedureResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspProfesionalSelResult : ProcedureResult {
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        private EstspProfesionalSelTProfesionales[] profesionalesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("profesionales", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public EstspProfesionalSelTProfesionales[] profesionales {
            get {
                return this.profesionalesField;
            }
            set {
                this.profesionalesField = value;
                this.RaisePropertyChanged("profesionales");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspAreaSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspAreaSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEstnuUsuarioId;
        
        public estspAreaSelRequest() {
        }
        
        public estspAreaSelRequest(decimal piEstnuUsuarioId) {
            this.piEstnuUsuarioId = piEstnuUsuarioId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspAreaSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspAreaSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.EstspAreaSelResult estspAreaSelResult;
        
        public estspAreaSelResponse() {
        }
        
        public estspAreaSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.EstspAreaSelResult estspAreaSelResult) {
            this.estspAreaSelResult = estspAreaSelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspProfesionalSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspProfesionalSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piEstnuUsuarioId;
        
        public estspProfesionalSelRequest() {
        }
        
        public estspProfesionalSelRequest(decimal piEstnuUsuarioId) {
            this.piEstnuUsuarioId = piEstnuUsuarioId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspProfesionalSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspProfesionalSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.EstspProfesionalSelResult estspProfesionalSelResult;
        
        public estspProfesionalSelResponse() {
        }
        
        public estspProfesionalSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.EstspProfesionalSelResult estspProfesionalSelResult) {
            this.estspProfesionalSelResult = estspProfesionalSelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsfiltrosestadisticasWebChannel : Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.WsfiltrosestadisticasWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsfiltrosestadisticasWebClient : System.ServiceModel.ClientBase<Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.WsfiltrosestadisticasWeb>, Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.WsfiltrosestadisticasWeb {
        
        public WsfiltrosestadisticasWebClient() {
        }
        
        public WsfiltrosestadisticasWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsfiltrosestadisticasWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsfiltrosestadisticasWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsfiltrosestadisticasWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspAreaSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.WsfiltrosestadisticasWeb.estspAreaSel(Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspAreaSelRequest request) {
            return base.Channel.estspAreaSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.EstspAreaSelResult estspAreaSel(decimal piEstnuUsuarioId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspAreaSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspAreaSelRequest();
            inValue.piEstnuUsuarioId = piEstnuUsuarioId;
            Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspAreaSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.WsfiltrosestadisticasWeb)(this)).estspAreaSel(inValue);
            return retVal.estspAreaSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspAreaSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.WsfiltrosestadisticasWeb.estspAreaSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspAreaSelRequest request) {
            return base.Channel.estspAreaSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspAreaSelResponse> estspAreaSelAsync(decimal piEstnuUsuarioId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspAreaSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspAreaSelRequest();
            inValue.piEstnuUsuarioId = piEstnuUsuarioId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.WsfiltrosestadisticasWeb)(this)).estspAreaSelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspProfesionalSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.WsfiltrosestadisticasWeb.estspProfesionalSel(Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspProfesionalSelRequest request) {
            return base.Channel.estspProfesionalSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.EstspProfesionalSelResult estspProfesionalSel(decimal piEstnuUsuarioId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspProfesionalSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspProfesionalSelRequest();
            inValue.piEstnuUsuarioId = piEstnuUsuarioId;
            Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspProfesionalSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.WsfiltrosestadisticasWeb)(this)).estspProfesionalSel(inValue);
            return retVal.estspProfesionalSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspProfesionalSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.WsfiltrosestadisticasWeb.estspProfesionalSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspProfesionalSelRequest request) {
            return base.Channel.estspProfesionalSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspProfesionalSelResponse> estspProfesionalSelAsync(decimal piEstnuUsuarioId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspProfesionalSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.estspProfesionalSelRequest();
            inValue.piEstnuUsuarioId = piEstnuUsuarioId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsFiltros.WsfiltrosestadisticasWeb)(this)).estspProfesionalSelAsync(inValue);
        }
    }
}
