//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nucleo.alemana.cl/", ConfigurationName="WsIndicadores.WsindicadoresestadisticasWeb")]
    public interface WsindicadoresestadisticasWeb {
        
        // CODEGEN: El parámetro 'estspIndCanVirtualSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndCanVirtualSelResponse estspIndCanVirtualSel(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndCanVirtualSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndCanVirtualSelResponse> estspIndCanVirtualSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndCanVirtualSelRequest request);
        
        // CODEGEN: El parámetro 'estspIndDiagnosticoSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndDiagnosticoSelResponse estspIndDiagnosticoSel(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndDiagnosticoSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndDiagnosticoSelResponse> estspIndDiagnosticoSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndDiagnosticoSelRequest request);
        
        // CODEGEN: El parámetro 'estspIndIndicadoresSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndIndicadoresSelResponse estspIndIndicadoresSel(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndIndicadoresSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndIndicadoresSelResponse> estspIndIndicadoresSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndIndicadoresSelRequest request);
        
        // CODEGEN: El parámetro 'estspIndPacienteSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndPacienteSelResponse estspIndPacienteSel(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndPacienteSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndPacienteSelResponse> estspIndPacienteSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndPacienteSelRequest request);
        
        // CODEGEN: El parámetro 'estspPacientesDiagSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPacientesDiagSelResponse estspPacientesDiagSel(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPacientesDiagSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPacientesDiagSelResponse> estspPacientesDiagSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPacientesDiagSelRequest request);
        
        // CODEGEN: El parámetro 'estspPpnidPacientesSelResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPpnidPacientesSelResponse estspPpnidPacientesSel(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPpnidPacientesSelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPpnidPacientesSelResponse> estspPpnidPacientesSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPpnidPacientesSelRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspIndCanVirtualSelResult : ProcedureResult {
        
        private EstspIndCanVirtualSelTIndicadoresCanalesVirtuales[] indicadoresCanalesVirtualesField;
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("indicadoresCanalesVirtuales", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public EstspIndCanVirtualSelTIndicadoresCanalesVirtuales[] indicadoresCanalesVirtuales {
            get {
                return this.indicadoresCanalesVirtualesField;
            }
            set {
                this.indicadoresCanalesVirtualesField = value;
                this.RaisePropertyChanged("indicadoresCanalesVirtuales");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspIndCanVirtualSelTIndicadoresCanalesVirtuales : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal fipnuPersonaIdField;
        
        private bool fipnuPersonaIdFieldSpecified;
        
        private System.DateTime msjdaFechaField;
        
        private bool msjdaFechaFieldSpecified;
        
        private decimal msjnuEstadoLecturaField;
        
        private bool msjnuEstadoLecturaFieldSpecified;
        
        private decimal msjnuEstadoMensajeField;
        
        private bool msjnuEstadoMensajeFieldSpecified;
        
        private decimal msjnuFuenteField;
        
        private bool msjnuFuenteFieldSpecified;
        
        private decimal msjnuMensajeIdField;
        
        private bool msjnuMensajeIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal fipnuPersonaId {
            get {
                return this.fipnuPersonaIdField;
            }
            set {
                this.fipnuPersonaIdField = value;
                this.RaisePropertyChanged("fipnuPersonaId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fipnuPersonaIdSpecified {
            get {
                return this.fipnuPersonaIdFieldSpecified;
            }
            set {
                this.fipnuPersonaIdFieldSpecified = value;
                this.RaisePropertyChanged("fipnuPersonaIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime msjdaFecha {
            get {
                return this.msjdaFechaField;
            }
            set {
                this.msjdaFechaField = value;
                this.RaisePropertyChanged("msjdaFecha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool msjdaFechaSpecified {
            get {
                return this.msjdaFechaFieldSpecified;
            }
            set {
                this.msjdaFechaFieldSpecified = value;
                this.RaisePropertyChanged("msjdaFechaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal msjnuEstadoLectura {
            get {
                return this.msjnuEstadoLecturaField;
            }
            set {
                this.msjnuEstadoLecturaField = value;
                this.RaisePropertyChanged("msjnuEstadoLectura");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool msjnuEstadoLecturaSpecified {
            get {
                return this.msjnuEstadoLecturaFieldSpecified;
            }
            set {
                this.msjnuEstadoLecturaFieldSpecified = value;
                this.RaisePropertyChanged("msjnuEstadoLecturaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal msjnuEstadoMensaje {
            get {
                return this.msjnuEstadoMensajeField;
            }
            set {
                this.msjnuEstadoMensajeField = value;
                this.RaisePropertyChanged("msjnuEstadoMensaje");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool msjnuEstadoMensajeSpecified {
            get {
                return this.msjnuEstadoMensajeFieldSpecified;
            }
            set {
                this.msjnuEstadoMensajeFieldSpecified = value;
                this.RaisePropertyChanged("msjnuEstadoMensajeSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal msjnuFuente {
            get {
                return this.msjnuFuenteField;
            }
            set {
                this.msjnuFuenteField = value;
                this.RaisePropertyChanged("msjnuFuente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool msjnuFuenteSpecified {
            get {
                return this.msjnuFuenteFieldSpecified;
            }
            set {
                this.msjnuFuenteFieldSpecified = value;
                this.RaisePropertyChanged("msjnuFuenteSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal msjnuMensajeId {
            get {
                return this.msjnuMensajeIdField;
            }
            set {
                this.msjnuMensajeIdField = value;
                this.RaisePropertyChanged("msjnuMensajeId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool msjnuMensajeIdSpecified {
            get {
                return this.msjnuMensajeIdFieldSpecified;
            }
            set {
                this.msjnuMensajeIdFieldSpecified = value;
                this.RaisePropertyChanged("msjnuMensajeIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspIndDiagnosticoSelTIndicadoresDiagnosticos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private string nombreField;
        
        private decimal numeroField;
        
        private bool numeroFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroSpecified {
            get {
                return this.numeroFieldSpecified;
            }
            set {
                this.numeroFieldSpecified = value;
                this.RaisePropertyChanged("numeroSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspIndIndicadoresSelTIndicadoresIndicaciones : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal farmacologiaField;
        
        private bool farmacologiaFieldSpecified;
        
        private decimal imagenologiaField;
        
        private bool imagenologiaFieldSpecified;
        
        private decimal laboratorioField;
        
        private bool laboratorioFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal farmacologia {
            get {
                return this.farmacologiaField;
            }
            set {
                this.farmacologiaField = value;
                this.RaisePropertyChanged("farmacologia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool farmacologiaSpecified {
            get {
                return this.farmacologiaFieldSpecified;
            }
            set {
                this.farmacologiaFieldSpecified = value;
                this.RaisePropertyChanged("farmacologiaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal imagenologia {
            get {
                return this.imagenologiaField;
            }
            set {
                this.imagenologiaField = value;
                this.RaisePropertyChanged("imagenologia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imagenologiaSpecified {
            get {
                return this.imagenologiaFieldSpecified;
            }
            set {
                this.imagenologiaFieldSpecified = value;
                this.RaisePropertyChanged("imagenologiaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal laboratorio {
            get {
                return this.laboratorioField;
            }
            set {
                this.laboratorioField = value;
                this.RaisePropertyChanged("laboratorio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool laboratorioSpecified {
            get {
                return this.laboratorioFieldSpecified;
            }
            set {
                this.laboratorioFieldSpecified = value;
                this.RaisePropertyChanged("laboratorioSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspPacientesDiagSelTPacientesDiagnostico : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspPpnidPacientesSelTPpnidPacientes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal usunuPersonaIdField;
        
        private bool usunuPersonaIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal usunuPersonaId {
            get {
                return this.usunuPersonaIdField;
            }
            set {
                this.usunuPersonaIdField = value;
                this.RaisePropertyChanged("usunuPersonaId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usunuPersonaIdSpecified {
            get {
                return this.usunuPersonaIdFieldSpecified;
            }
            set {
                this.usunuPersonaIdFieldSpecified = value;
                this.RaisePropertyChanged("usunuPersonaIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspIndPacienteSelTIndicadoresPacientes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal atendidosField;
        
        private bool atendidosFieldSpecified;
        
        private decimal etiquetadosField;
        
        private bool etiquetadosFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal atendidos {
            get {
                return this.atendidosField;
            }
            set {
                this.atendidosField = value;
                this.RaisePropertyChanged("atendidos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool atendidosSpecified {
            get {
                return this.atendidosFieldSpecified;
            }
            set {
                this.atendidosFieldSpecified = value;
                this.RaisePropertyChanged("atendidosSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal etiquetados {
            get {
                return this.etiquetadosField;
            }
            set {
                this.etiquetadosField = value;
                this.RaisePropertyChanged("etiquetados");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool etiquetadosSpecified {
            get {
                return this.etiquetadosFieldSpecified;
            }
            set {
                this.etiquetadosFieldSpecified = value;
                this.RaisePropertyChanged("etiquetadosSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstspIndDiagnosticoSelResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstspIndIndicadoresSelResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstspPacientesDiagSelResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstspPpnidPacientesSelResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstspIndCanVirtualSelResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstspIndPacienteSelResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public abstract partial class ProcedureResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspIndDiagnosticoSelResult : ProcedureResult {
        
        private EstspIndDiagnosticoSelTIndicadoresDiagnosticos[] indicadoresDiagnosticosField;
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("indicadoresDiagnosticos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public EstspIndDiagnosticoSelTIndicadoresDiagnosticos[] indicadoresDiagnosticos {
            get {
                return this.indicadoresDiagnosticosField;
            }
            set {
                this.indicadoresDiagnosticosField = value;
                this.RaisePropertyChanged("indicadoresDiagnosticos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspIndIndicadoresSelResult : ProcedureResult {
        
        private EstspIndIndicadoresSelTIndicadoresIndicaciones[] indicadoresIndicacionesField;
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("indicadoresIndicaciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public EstspIndIndicadoresSelTIndicadoresIndicaciones[] indicadoresIndicaciones {
            get {
                return this.indicadoresIndicacionesField;
            }
            set {
                this.indicadoresIndicacionesField = value;
                this.RaisePropertyChanged("indicadoresIndicaciones");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspPacientesDiagSelResult : ProcedureResult {
        
        private EstspPacientesDiagSelTPacientesDiagnostico[] pacientesDiagnosticoField;
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("pacientesDiagnostico", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public EstspPacientesDiagSelTPacientesDiagnostico[] pacientesDiagnostico {
            get {
                return this.pacientesDiagnosticoField;
            }
            set {
                this.pacientesDiagnosticoField = value;
                this.RaisePropertyChanged("pacientesDiagnostico");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspPpnidPacientesSelResult : ProcedureResult {
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        private EstspPpnidPacientesSelTPpnidPacientes[] ppnidPacientesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ppnidPacientes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public EstspPpnidPacientesSelTPpnidPacientes[] ppnidPacientes {
            get {
                return this.ppnidPacientesField;
            }
            set {
                this.ppnidPacientesField = value;
                this.RaisePropertyChanged("ppnidPacientes");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class EstspIndPacienteSelResult : ProcedureResult {
        
        private EstspIndPacienteSelTIndicadoresPacientes[] indicadoresPacientesField;
        
        private decimal poFcenuCodretField;
        
        private bool poFcenuCodretFieldSpecified;
        
        private string poFcevaDesretField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("indicadoresPacientes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public EstspIndPacienteSelTIndicadoresPacientes[] indicadoresPacientes {
            get {
                return this.indicadoresPacientesField;
            }
            set {
                this.indicadoresPacientesField = value;
                this.RaisePropertyChanged("indicadoresPacientes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal poFcenuCodret {
            get {
                return this.poFcenuCodretField;
            }
            set {
                this.poFcenuCodretField = value;
                this.RaisePropertyChanged("poFcenuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poFcenuCodretSpecified {
            get {
                return this.poFcenuCodretFieldSpecified;
            }
            set {
                this.poFcenuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poFcenuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poFcevaDesret {
            get {
                return this.poFcevaDesretField;
            }
            set {
                this.poFcevaDesretField = value;
                this.RaisePropertyChanged("poFcevaDesret");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspIndCanVirtualSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspIndCanVirtualSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstUsuarios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstAreas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechainicioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechafinId;
        
        public estspIndCanVirtualSelRequest() {
        }
        
        public estspIndCanVirtualSelRequest(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId) {
            this.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            this.piEpsvaLstAreas = piEpsvaLstAreas;
            this.piEpsdtFechainicioId = piEpsdtFechainicioId;
            this.piEpsdtFechafinId = piEpsdtFechafinId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspIndCanVirtualSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspIndCanVirtualSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspIndCanVirtualSelResult estspIndCanVirtualSelResult;
        
        public estspIndCanVirtualSelResponse() {
        }
        
        public estspIndCanVirtualSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspIndCanVirtualSelResult estspIndCanVirtualSelResult) {
            this.estspIndCanVirtualSelResult = estspIndCanVirtualSelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspIndDiagnosticoSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspIndDiagnosticoSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstUsuarios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstAreas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechainicioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechafinId;
        
        public estspIndDiagnosticoSelRequest() {
        }
        
        public estspIndDiagnosticoSelRequest(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId) {
            this.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            this.piEpsvaLstAreas = piEpsvaLstAreas;
            this.piEpsdtFechainicioId = piEpsdtFechainicioId;
            this.piEpsdtFechafinId = piEpsdtFechafinId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspIndDiagnosticoSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspIndDiagnosticoSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspIndDiagnosticoSelResult estspIndDiagnosticoSelResult;
        
        public estspIndDiagnosticoSelResponse() {
        }
        
        public estspIndDiagnosticoSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspIndDiagnosticoSelResult estspIndDiagnosticoSelResult) {
            this.estspIndDiagnosticoSelResult = estspIndDiagnosticoSelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspIndIndicadoresSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspIndIndicadoresSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstUsuarios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstAreas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechainicioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechafinId;
        
        public estspIndIndicadoresSelRequest() {
        }
        
        public estspIndIndicadoresSelRequest(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId) {
            this.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            this.piEpsvaLstAreas = piEpsvaLstAreas;
            this.piEpsdtFechainicioId = piEpsdtFechainicioId;
            this.piEpsdtFechafinId = piEpsdtFechafinId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspIndIndicadoresSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspIndIndicadoresSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspIndIndicadoresSelResult estspIndIndicadoresSelResult;
        
        public estspIndIndicadoresSelResponse() {
        }
        
        public estspIndIndicadoresSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspIndIndicadoresSelResult estspIndIndicadoresSelResult) {
            this.estspIndIndicadoresSelResult = estspIndIndicadoresSelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspIndPacienteSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspIndPacienteSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstUsuarios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstAreas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechainicioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechafinId;
        
        public estspIndPacienteSelRequest() {
        }
        
        public estspIndPacienteSelRequest(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId) {
            this.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            this.piEpsvaLstAreas = piEpsvaLstAreas;
            this.piEpsdtFechainicioId = piEpsdtFechainicioId;
            this.piEpsdtFechafinId = piEpsdtFechafinId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspIndPacienteSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspIndPacienteSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspIndPacienteSelResult estspIndPacienteSelResult;
        
        public estspIndPacienteSelResponse() {
        }
        
        public estspIndPacienteSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspIndPacienteSelResult estspIndPacienteSelResult) {
            this.estspIndPacienteSelResult = estspIndPacienteSelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspPacientesDiagSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspPacientesDiagSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstUsuarios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstAreas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechainicioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piEpsdtFechafinId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piCctnuDescriptionId;
        
        public estspPacientesDiagSelRequest() {
        }
        
        public estspPacientesDiagSelRequest(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId, decimal piCctnuDescriptionId) {
            this.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            this.piEpsvaLstAreas = piEpsvaLstAreas;
            this.piEpsdtFechainicioId = piEpsdtFechainicioId;
            this.piEpsdtFechafinId = piEpsdtFechafinId;
            this.piCctnuDescriptionId = piCctnuDescriptionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspPacientesDiagSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspPacientesDiagSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspPacientesDiagSelResult estspPacientesDiagSelResult;
        
        public estspPacientesDiagSelResponse() {
        }
        
        public estspPacientesDiagSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspPacientesDiagSelResult estspPacientesDiagSelResult) {
            this.estspPacientesDiagSelResult = estspPacientesDiagSelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspPpnidPacientesSel", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspPpnidPacientesSelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstUsuarios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piEpsvaLstAreas;
        
        public estspPpnidPacientesSelRequest() {
        }
        
        public estspPpnidPacientesSelRequest(string piEpsvaLstUsuarios, string piEpsvaLstAreas) {
            this.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            this.piEpsvaLstAreas = piEpsvaLstAreas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="estspPpnidPacientesSelResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class estspPpnidPacientesSelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspPpnidPacientesSelResult estspPpnidPacientesSelResult;
        
        public estspPpnidPacientesSelResponse() {
        }
        
        public estspPpnidPacientesSelResponse(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspPpnidPacientesSelResult estspPpnidPacientesSelResult) {
            this.estspPpnidPacientesSelResult = estspPpnidPacientesSelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsindicadoresestadisticasWebChannel : Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsindicadoresestadisticasWebClient : System.ServiceModel.ClientBase<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb>, Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb {
        
        public WsindicadoresestadisticasWebClient() {
        }
        
        public WsindicadoresestadisticasWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsindicadoresestadisticasWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsindicadoresestadisticasWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsindicadoresestadisticasWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndCanVirtualSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb.estspIndCanVirtualSel(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndCanVirtualSelRequest request) {
            return base.Channel.estspIndCanVirtualSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspIndCanVirtualSelResult estspIndCanVirtualSel(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndCanVirtualSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndCanVirtualSelRequest();
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndCanVirtualSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb)(this)).estspIndCanVirtualSel(inValue);
            return retVal.estspIndCanVirtualSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndCanVirtualSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb.estspIndCanVirtualSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndCanVirtualSelRequest request) {
            return base.Channel.estspIndCanVirtualSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndCanVirtualSelResponse> estspIndCanVirtualSelAsync(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndCanVirtualSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndCanVirtualSelRequest();
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb)(this)).estspIndCanVirtualSelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndDiagnosticoSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb.estspIndDiagnosticoSel(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndDiagnosticoSelRequest request) {
            return base.Channel.estspIndDiagnosticoSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspIndDiagnosticoSelResult estspIndDiagnosticoSel(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndDiagnosticoSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndDiagnosticoSelRequest();
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndDiagnosticoSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb)(this)).estspIndDiagnosticoSel(inValue);
            return retVal.estspIndDiagnosticoSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndDiagnosticoSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb.estspIndDiagnosticoSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndDiagnosticoSelRequest request) {
            return base.Channel.estspIndDiagnosticoSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndDiagnosticoSelResponse> estspIndDiagnosticoSelAsync(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndDiagnosticoSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndDiagnosticoSelRequest();
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb)(this)).estspIndDiagnosticoSelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndIndicadoresSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb.estspIndIndicadoresSel(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndIndicadoresSelRequest request) {
            return base.Channel.estspIndIndicadoresSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspIndIndicadoresSelResult estspIndIndicadoresSel(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndIndicadoresSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndIndicadoresSelRequest();
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndIndicadoresSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb)(this)).estspIndIndicadoresSel(inValue);
            return retVal.estspIndIndicadoresSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndIndicadoresSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb.estspIndIndicadoresSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndIndicadoresSelRequest request) {
            return base.Channel.estspIndIndicadoresSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndIndicadoresSelResponse> estspIndIndicadoresSelAsync(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndIndicadoresSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndIndicadoresSelRequest();
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb)(this)).estspIndIndicadoresSelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndPacienteSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb.estspIndPacienteSel(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndPacienteSelRequest request) {
            return base.Channel.estspIndPacienteSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspIndPacienteSelResult estspIndPacienteSel(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndPacienteSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndPacienteSelRequest();
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndPacienteSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb)(this)).estspIndPacienteSel(inValue);
            return retVal.estspIndPacienteSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndPacienteSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb.estspIndPacienteSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndPacienteSelRequest request) {
            return base.Channel.estspIndPacienteSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndPacienteSelResponse> estspIndPacienteSelAsync(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndPacienteSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspIndPacienteSelRequest();
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb)(this)).estspIndPacienteSelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPacientesDiagSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb.estspPacientesDiagSel(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPacientesDiagSelRequest request) {
            return base.Channel.estspPacientesDiagSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspPacientesDiagSelResult estspPacientesDiagSel(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId, decimal piCctnuDescriptionId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPacientesDiagSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPacientesDiagSelRequest();
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            inValue.piCctnuDescriptionId = piCctnuDescriptionId;
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPacientesDiagSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb)(this)).estspPacientesDiagSel(inValue);
            return retVal.estspPacientesDiagSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPacientesDiagSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb.estspPacientesDiagSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPacientesDiagSelRequest request) {
            return base.Channel.estspPacientesDiagSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPacientesDiagSelResponse> estspPacientesDiagSelAsync(string piEpsvaLstUsuarios, string piEpsvaLstAreas, System.DateTime piEpsdtFechainicioId, System.DateTime piEpsdtFechafinId, decimal piCctnuDescriptionId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPacientesDiagSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPacientesDiagSelRequest();
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            inValue.piEpsdtFechainicioId = piEpsdtFechainicioId;
            inValue.piEpsdtFechafinId = piEpsdtFechafinId;
            inValue.piCctnuDescriptionId = piCctnuDescriptionId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb)(this)).estspPacientesDiagSelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPpnidPacientesSelResponse Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb.estspPpnidPacientesSel(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPpnidPacientesSelRequest request) {
            return base.Channel.estspPpnidPacientesSel(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.EstspPpnidPacientesSelResult estspPpnidPacientesSel(string piEpsvaLstUsuarios, string piEpsvaLstAreas) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPpnidPacientesSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPpnidPacientesSelRequest();
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPpnidPacientesSelResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb)(this)).estspPpnidPacientesSel(inValue);
            return retVal.estspPpnidPacientesSelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPpnidPacientesSelResponse> Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb.estspPpnidPacientesSelAsync(Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPpnidPacientesSelRequest request) {
            return base.Channel.estspPpnidPacientesSelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPpnidPacientesSelResponse> estspPpnidPacientesSelAsync(string piEpsvaLstUsuarios, string piEpsvaLstAreas) {
            Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPpnidPacientesSelRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.estspPpnidPacientesSelRequest();
            inValue.piEpsvaLstUsuarios = piEpsvaLstUsuarios;
            inValue.piEpsvaLstAreas = piEpsvaLstAreas;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsIndicadores.WsindicadoresestadisticasWeb)(this)).estspPpnidPacientesSelAsync(inValue);
        }
    }
}
