//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nucleo.alemana.cl/", ConfigurationName="WsAuditoriaGestionServiceReference.WsauditoriagestionWeb")]
    public interface WsauditoriagestionWeb {
        
        // CODEGEN: El parámetro 'fcespFcetmImpresionInsResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFcetmImpresionInsResponse fcespFcetmImpresionIns(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFcetmImpresionInsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFcetmImpresionInsResponse> fcespFcetmImpresionInsAsync(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFcetmImpresionInsRequest request);
        
        // CODEGEN: El parámetro 'fcespFinalizaAuditoriaResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFinalizaAuditoriaResponse fcespFinalizaAuditoria(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFinalizaAuditoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFinalizaAuditoriaResponse> fcespFinalizaAuditoriaAsync(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFinalizaAuditoriaRequest request);
        
        // CODEGEN: El parámetro 'fcespIniciaAuditoriaResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespIniciaAuditoriaResponse fcespIniciaAuditoria(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespIniciaAuditoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespIniciaAuditoriaResponse> fcespIniciaAuditoriaAsync(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespIniciaAuditoriaRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class FcespFcetmImpresionInsResult : ProcedureResult {
        
        private decimal poImpnuReporteIdField;
        
        private bool poImpnuReporteIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal poImpnuReporteId {
            get {
                return this.poImpnuReporteIdField;
            }
            set {
                this.poImpnuReporteIdField = value;
                this.RaisePropertyChanged("poImpnuReporteId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poImpnuReporteIdSpecified {
            get {
                return this.poImpnuReporteIdFieldSpecified;
            }
            set {
                this.poImpnuReporteIdFieldSpecified = value;
                this.RaisePropertyChanged("poImpnuReporteIdSpecified");
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FcespIniciaAuditoriaResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FcespFcetmImpresionInsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FcespFinalizaAuditoriaResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public abstract partial class ProcedureResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class FcespIniciaAuditoriaResult : ProcedureResult {
        
        private decimal poAudnuAuditoriaIdField;
        
        private bool poAudnuAuditoriaIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal poAudnuAuditoriaId {
            get {
                return this.poAudnuAuditoriaIdField;
            }
            set {
                this.poAudnuAuditoriaIdField = value;
                this.RaisePropertyChanged("poAudnuAuditoriaId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poAudnuAuditoriaIdSpecified {
            get {
                return this.poAudnuAuditoriaIdFieldSpecified;
            }
            set {
                this.poAudnuAuditoriaIdFieldSpecified = value;
                this.RaisePropertyChanged("poAudnuAuditoriaIdSpecified");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class FcespFinalizaAuditoriaResult : ProcedureResult {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fcespFcetmImpresionIns", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class fcespFcetmImpresionInsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piImpvaNombreReporte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piImpvaDatosReporte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piImpnuSesionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piImpnuFichaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piImpnuEpisodioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piImpnuEncuentroId;
        
        public fcespFcetmImpresionInsRequest() {
        }
        
        public fcespFcetmImpresionInsRequest(string piImpvaNombreReporte, string piImpvaDatosReporte, decimal piImpnuSesionId, decimal piImpnuFichaId, decimal piImpnuEpisodioId, decimal piImpnuEncuentroId) {
            this.piImpvaNombreReporte = piImpvaNombreReporte;
            this.piImpvaDatosReporte = piImpvaDatosReporte;
            this.piImpnuSesionId = piImpnuSesionId;
            this.piImpnuFichaId = piImpnuFichaId;
            this.piImpnuEpisodioId = piImpnuEpisodioId;
            this.piImpnuEncuentroId = piImpnuEncuentroId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fcespFcetmImpresionInsResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class fcespFcetmImpresionInsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.FcespFcetmImpresionInsResult fcespFcetmImpresionInsResult;
        
        public fcespFcetmImpresionInsResponse() {
        }
        
        public fcespFcetmImpresionInsResponse(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.FcespFcetmImpresionInsResult fcespFcetmImpresionInsResult) {
            this.fcespFcetmImpresionInsResult = fcespFcetmImpresionInsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fcespFinalizaAuditoria", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class fcespFinalizaAuditoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piAudnuSesionId;
        
        public fcespFinalizaAuditoriaRequest() {
        }
        
        public fcespFinalizaAuditoriaRequest(decimal piAudnuSesionId) {
            this.piAudnuSesionId = piAudnuSesionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fcespFinalizaAuditoriaResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class fcespFinalizaAuditoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.FcespFinalizaAuditoriaResult fcespFinalizaAuditoriaResult;
        
        public fcespFinalizaAuditoriaResponse() {
        }
        
        public fcespFinalizaAuditoriaResponse(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.FcespFinalizaAuditoriaResult fcespFinalizaAuditoriaResult) {
            this.fcespFinalizaAuditoriaResult = fcespFinalizaAuditoriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fcespIniciaAuditoria", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class fcespIniciaAuditoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piAudvaModulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piAudnuSesionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piAudnuFichaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piAudnuEpisodioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piAudnuEncuentroId;
        
        public fcespIniciaAuditoriaRequest() {
        }
        
        public fcespIniciaAuditoriaRequest(string piAudvaModulo, decimal piAudnuSesionId, decimal piAudnuFichaId, decimal piAudnuEpisodioId, decimal piAudnuEncuentroId) {
            this.piAudvaModulo = piAudvaModulo;
            this.piAudnuSesionId = piAudnuSesionId;
            this.piAudnuFichaId = piAudnuFichaId;
            this.piAudnuEpisodioId = piAudnuEpisodioId;
            this.piAudnuEncuentroId = piAudnuEncuentroId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fcespIniciaAuditoriaResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class fcespIniciaAuditoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.FcespIniciaAuditoriaResult fcespIniciaAuditoriaResult;
        
        public fcespIniciaAuditoriaResponse() {
        }
        
        public fcespIniciaAuditoriaResponse(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.FcespIniciaAuditoriaResult fcespIniciaAuditoriaResult) {
            this.fcespIniciaAuditoriaResult = fcespIniciaAuditoriaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsauditoriagestionWebChannel : Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsauditoriagestionWebClient : System.ServiceModel.ClientBase<Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb>, Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb {
        
        public WsauditoriagestionWebClient() {
        }
        
        public WsauditoriagestionWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsauditoriagestionWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsauditoriagestionWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsauditoriagestionWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFcetmImpresionInsResponse Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb.fcespFcetmImpresionIns(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFcetmImpresionInsRequest request) {
            return base.Channel.fcespFcetmImpresionIns(request);
        }
        
        public Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.FcespFcetmImpresionInsResult fcespFcetmImpresionIns(string piImpvaNombreReporte, string piImpvaDatosReporte, decimal piImpnuSesionId, decimal piImpnuFichaId, decimal piImpnuEpisodioId, decimal piImpnuEncuentroId) {
            Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFcetmImpresionInsRequest inValue = new Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFcetmImpresionInsRequest();
            inValue.piImpvaNombreReporte = piImpvaNombreReporte;
            inValue.piImpvaDatosReporte = piImpvaDatosReporte;
            inValue.piImpnuSesionId = piImpnuSesionId;
            inValue.piImpnuFichaId = piImpnuFichaId;
            inValue.piImpnuEpisodioId = piImpnuEpisodioId;
            inValue.piImpnuEncuentroId = piImpnuEncuentroId;
            Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFcetmImpresionInsResponse retVal = ((Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb)(this)).fcespFcetmImpresionIns(inValue);
            return retVal.fcespFcetmImpresionInsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFcetmImpresionInsResponse> Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb.fcespFcetmImpresionInsAsync(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFcetmImpresionInsRequest request) {
            return base.Channel.fcespFcetmImpresionInsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFcetmImpresionInsResponse> fcespFcetmImpresionInsAsync(string piImpvaNombreReporte, string piImpvaDatosReporte, decimal piImpnuSesionId, decimal piImpnuFichaId, decimal piImpnuEpisodioId, decimal piImpnuEncuentroId) {
            Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFcetmImpresionInsRequest inValue = new Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFcetmImpresionInsRequest();
            inValue.piImpvaNombreReporte = piImpvaNombreReporte;
            inValue.piImpvaDatosReporte = piImpvaDatosReporte;
            inValue.piImpnuSesionId = piImpnuSesionId;
            inValue.piImpnuFichaId = piImpnuFichaId;
            inValue.piImpnuEpisodioId = piImpnuEpisodioId;
            inValue.piImpnuEncuentroId = piImpnuEncuentroId;
            return ((Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb)(this)).fcespFcetmImpresionInsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFinalizaAuditoriaResponse Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb.fcespFinalizaAuditoria(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFinalizaAuditoriaRequest request) {
            return base.Channel.fcespFinalizaAuditoria(request);
        }
        
        public Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.FcespFinalizaAuditoriaResult fcespFinalizaAuditoria(decimal piAudnuSesionId) {
            Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFinalizaAuditoriaRequest inValue = new Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFinalizaAuditoriaRequest();
            inValue.piAudnuSesionId = piAudnuSesionId;
            Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFinalizaAuditoriaResponse retVal = ((Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb)(this)).fcespFinalizaAuditoria(inValue);
            return retVal.fcespFinalizaAuditoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFinalizaAuditoriaResponse> Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb.fcespFinalizaAuditoriaAsync(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFinalizaAuditoriaRequest request) {
            return base.Channel.fcespFinalizaAuditoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFinalizaAuditoriaResponse> fcespFinalizaAuditoriaAsync(decimal piAudnuSesionId) {
            Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFinalizaAuditoriaRequest inValue = new Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespFinalizaAuditoriaRequest();
            inValue.piAudnuSesionId = piAudnuSesionId;
            return ((Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb)(this)).fcespFinalizaAuditoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespIniciaAuditoriaResponse Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb.fcespIniciaAuditoria(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespIniciaAuditoriaRequest request) {
            return base.Channel.fcespIniciaAuditoria(request);
        }
        
        public Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.FcespIniciaAuditoriaResult fcespIniciaAuditoria(string piAudvaModulo, decimal piAudnuSesionId, decimal piAudnuFichaId, decimal piAudnuEpisodioId, decimal piAudnuEncuentroId) {
            Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespIniciaAuditoriaRequest inValue = new Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespIniciaAuditoriaRequest();
            inValue.piAudvaModulo = piAudvaModulo;
            inValue.piAudnuSesionId = piAudnuSesionId;
            inValue.piAudnuFichaId = piAudnuFichaId;
            inValue.piAudnuEpisodioId = piAudnuEpisodioId;
            inValue.piAudnuEncuentroId = piAudnuEncuentroId;
            Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespIniciaAuditoriaResponse retVal = ((Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb)(this)).fcespIniciaAuditoria(inValue);
            return retVal.fcespIniciaAuditoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespIniciaAuditoriaResponse> Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb.fcespIniciaAuditoriaAsync(Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespIniciaAuditoriaRequest request) {
            return base.Channel.fcespIniciaAuditoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespIniciaAuditoriaResponse> fcespIniciaAuditoriaAsync(string piAudvaModulo, decimal piAudnuSesionId, decimal piAudnuFichaId, decimal piAudnuEpisodioId, decimal piAudnuEncuentroId) {
            Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespIniciaAuditoriaRequest inValue = new Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.fcespIniciaAuditoriaRequest();
            inValue.piAudvaModulo = piAudvaModulo;
            inValue.piAudnuSesionId = piAudnuSesionId;
            inValue.piAudnuFichaId = piAudnuFichaId;
            inValue.piAudnuEpisodioId = piAudnuEpisodioId;
            inValue.piAudnuEncuentroId = piAudnuEncuentroId;
            return ((Alemana.Nucleo.Common.WsAuditoriaGestionServiceReference.WsauditoriagestionWeb)(this)).fcespIniciaAuditoriaAsync(inValue);
        }
    }
}
