//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nucleo.alemana.cl/", ConfigurationName="WsAgendaMedica.WsagendamedicaWeb")]
    public interface WsagendamedicaWeb {
        
        // CODEGEN: El parámetro 'indspRecetaCrearResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaCrearResponse indspRecetaCrear(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaCrearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaCrearResponse> indspRecetaCrearAsync(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaCrearRequest request);
        
        // CODEGEN: El parámetro 'indspRecetaExpirarResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaExpirarResponse indspRecetaExpirar(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaExpirarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaExpirarResponse> indspRecetaExpirarAsync(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaExpirarRequest request);
        
        // CODEGEN: El parámetro 'indspRecetaIndicacionInsResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaIndicacionInsResponse indspRecetaIndicacionIns(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaIndicacionInsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaIndicacionInsResponse> indspRecetaIndicacionInsAsync(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaIndicacionInsRequest request);
        
        // CODEGEN: El parámetro 'indspRecetaInsResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaInsResponse indspRecetaIns(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaInsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaInsResponse> indspRecetaInsAsync(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaInsRequest request);
        
        // CODEGEN: El parámetro 'indspRecetaRenovarResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaRenovarResponse indspRecetaRenovar(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaRenovarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaRenovarResponse> indspRecetaRenovarAsync(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaRenovarRequest request);
        
        // CODEGEN: El parámetro 'intspCantidadEstadosResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="faultInfo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcedureResult))]
        Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.intspCantidadEstadosResponse intspCantidadEstados(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.intspCantidadEstadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.intspCantidadEstadosResponse> intspCantidadEstadosAsync(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.intspCantidadEstadosRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class IndspRecetaCrearResult : ProcedureResult {
        
        private decimal poIndnuRecetaIdField;
        
        private bool poIndnuRecetaIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal poIndnuRecetaId {
            get {
                return this.poIndnuRecetaIdField;
            }
            set {
                this.poIndnuRecetaIdField = value;
                this.RaisePropertyChanged("poIndnuRecetaId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poIndnuRecetaIdSpecified {
            get {
                return this.poIndnuRecetaIdFieldSpecified;
            }
            set {
                this.poIndnuRecetaIdFieldSpecified = value;
                this.RaisePropertyChanged("poIndnuRecetaIdSpecified");
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IndspRecetaCrearResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IndspRecetaIndicacionInsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IndspRecetaInsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntspCantidadEstadosResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IndspRecetaExpirarResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IndspRecetaRenovarResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public abstract partial class ProcedureResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class IndspRecetaIndicacionInsResult : ProcedureResult {
        
        private decimal poIndnuRecetaIndicacionIdField;
        
        private bool poIndnuRecetaIndicacionIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal poIndnuRecetaIndicacionId {
            get {
                return this.poIndnuRecetaIndicacionIdField;
            }
            set {
                this.poIndnuRecetaIndicacionIdField = value;
                this.RaisePropertyChanged("poIndnuRecetaIndicacionId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poIndnuRecetaIndicacionIdSpecified {
            get {
                return this.poIndnuRecetaIndicacionIdFieldSpecified;
            }
            set {
                this.poIndnuRecetaIndicacionIdFieldSpecified = value;
                this.RaisePropertyChanged("poIndnuRecetaIndicacionIdSpecified");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class IndspRecetaInsResult : ProcedureResult {
        
        private decimal poIndnuRecetaIdField;
        
        private bool poIndnuRecetaIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal poIndnuRecetaId {
            get {
                return this.poIndnuRecetaIdField;
            }
            set {
                this.poIndnuRecetaIdField = value;
                this.RaisePropertyChanged("poIndnuRecetaId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poIndnuRecetaIdSpecified {
            get {
                return this.poIndnuRecetaIdFieldSpecified;
            }
            set {
                this.poIndnuRecetaIdFieldSpecified = value;
                this.RaisePropertyChanged("poIndnuRecetaIdSpecified");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class IntspCantidadEstadosResult : ProcedureResult {
        
        private decimal poIntnuCantidadField;
        
        private bool poIntnuCantidadFieldSpecified;
        
        private decimal poIntnuCodretField;
        
        private bool poIntnuCodretFieldSpecified;
        
        private string poIntvaDesretField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal poIntnuCantidad {
            get {
                return this.poIntnuCantidadField;
            }
            set {
                this.poIntnuCantidadField = value;
                this.RaisePropertyChanged("poIntnuCantidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poIntnuCantidadSpecified {
            get {
                return this.poIntnuCantidadFieldSpecified;
            }
            set {
                this.poIntnuCantidadFieldSpecified = value;
                this.RaisePropertyChanged("poIntnuCantidadSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal poIntnuCodret {
            get {
                return this.poIntnuCodretField;
            }
            set {
                this.poIntnuCodretField = value;
                this.RaisePropertyChanged("poIntnuCodret");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poIntnuCodretSpecified {
            get {
                return this.poIntnuCodretFieldSpecified;
            }
            set {
                this.poIntnuCodretFieldSpecified = value;
                this.RaisePropertyChanged("poIntnuCodretSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string poIntvaDesret {
            get {
                return this.poIntvaDesretField;
            }
            set {
                this.poIntvaDesretField = value;
                this.RaisePropertyChanged("poIntvaDesret");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class IndspRecetaExpirarResult : ProcedureResult {
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nucleo.alemana.cl/")]
    public partial class IndspRecetaRenovarResult : ProcedureResult {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="indspRecetaCrear", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class indspRecetaCrearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piIndnuReporteId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piInddaFechaReceta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piIndnuUsuarioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piIndnuCreadorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piIndvaIndicacionesArray;
        
        public indspRecetaCrearRequest() {
        }
        
        public indspRecetaCrearRequest(decimal piIndnuReporteId, System.DateTime piInddaFechaReceta, decimal piIndnuUsuarioId, decimal piIndnuCreadorId, string piIndvaIndicacionesArray) {
            this.piIndnuReporteId = piIndnuReporteId;
            this.piInddaFechaReceta = piInddaFechaReceta;
            this.piIndnuUsuarioId = piIndnuUsuarioId;
            this.piIndnuCreadorId = piIndnuCreadorId;
            this.piIndvaIndicacionesArray = piIndvaIndicacionesArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="indspRecetaCrearResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class indspRecetaCrearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaCrearResult indspRecetaCrearResult;
        
        public indspRecetaCrearResponse() {
        }
        
        public indspRecetaCrearResponse(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaCrearResult indspRecetaCrearResult) {
            this.indspRecetaCrearResult = indspRecetaCrearResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="indspRecetaExpirar", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class indspRecetaExpirarRequest {
        
        public indspRecetaExpirarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="indspRecetaExpirarResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class indspRecetaExpirarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaExpirarResult indspRecetaExpirarResult;
        
        public indspRecetaExpirarResponse() {
        }
        
        public indspRecetaExpirarResponse(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaExpirarResult indspRecetaExpirarResult) {
            this.indspRecetaExpirarResult = indspRecetaExpirarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="indspRecetaIndicacionIns", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class indspRecetaIndicacionInsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piIndnuRecetaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piIndnuIndicacionesId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piIndnuCreadorId;
        
        public indspRecetaIndicacionInsRequest() {
        }
        
        public indspRecetaIndicacionInsRequest(decimal piIndnuRecetaId, decimal piIndnuIndicacionesId, decimal piIndnuCreadorId) {
            this.piIndnuRecetaId = piIndnuRecetaId;
            this.piIndnuIndicacionesId = piIndnuIndicacionesId;
            this.piIndnuCreadorId = piIndnuCreadorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="indspRecetaIndicacionInsResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class indspRecetaIndicacionInsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaIndicacionInsResult indspRecetaIndicacionInsResult;
        
        public indspRecetaIndicacionInsResponse() {
        }
        
        public indspRecetaIndicacionInsResponse(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaIndicacionInsResult indspRecetaIndicacionInsResult) {
            this.indspRecetaIndicacionInsResult = indspRecetaIndicacionInsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="indspRecetaIns", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class indspRecetaInsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piIndnuReporteId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piInddaFechaReceta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piIndnuUsuarioId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piIndnuCreadorId;
        
        public indspRecetaInsRequest() {
        }
        
        public indspRecetaInsRequest(decimal piIndnuReporteId, System.DateTime piInddaFechaReceta, decimal piIndnuUsuarioId, decimal piIndnuCreadorId) {
            this.piIndnuReporteId = piIndnuReporteId;
            this.piInddaFechaReceta = piInddaFechaReceta;
            this.piIndnuUsuarioId = piIndnuUsuarioId;
            this.piIndnuCreadorId = piIndnuCreadorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="indspRecetaInsResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class indspRecetaInsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaInsResult indspRecetaInsResult;
        
        public indspRecetaInsResponse() {
        }
        
        public indspRecetaInsResponse(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaInsResult indspRecetaInsResult) {
            this.indspRecetaInsResult = indspRecetaInsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="indspRecetaRenovar", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class indspRecetaRenovarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piIndnuRecetaId;
        
        public indspRecetaRenovarRequest() {
        }
        
        public indspRecetaRenovarRequest(decimal piIndnuRecetaId) {
            this.piIndnuRecetaId = piIndnuRecetaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="indspRecetaRenovarResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class indspRecetaRenovarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaRenovarResult indspRecetaRenovarResult;
        
        public indspRecetaRenovarResponse() {
        }
        
        public indspRecetaRenovarResponse(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaRenovarResult indspRecetaRenovarResult) {
            this.indspRecetaRenovarResult = indspRecetaRenovarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="intspCantidadEstados", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class intspCantidadEstadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal piIntvaIdAgenda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piIntdaFechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime piIntdaFechaFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piIntvaLstUsuarios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string piIntvaLstAreas;
        
        public intspCantidadEstadosRequest() {
        }
        
        public intspCantidadEstadosRequest(decimal piIntvaIdAgenda, System.DateTime piIntdaFechaInicio, System.DateTime piIntdaFechaFin, string piIntvaLstUsuarios, string piIntvaLstAreas) {
            this.piIntvaIdAgenda = piIntvaIdAgenda;
            this.piIntdaFechaInicio = piIntdaFechaInicio;
            this.piIntdaFechaFin = piIntdaFechaFin;
            this.piIntvaLstUsuarios = piIntvaLstUsuarios;
            this.piIntvaLstAreas = piIntvaLstAreas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="intspCantidadEstadosResponse", WrapperNamespace="http://nucleo.alemana.cl/", IsWrapped=true)]
    public partial class intspCantidadEstadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nucleo.alemana.cl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IntspCantidadEstadosResult intspCantidadEstadosResult;
        
        public intspCantidadEstadosResponse() {
        }
        
        public intspCantidadEstadosResponse(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IntspCantidadEstadosResult intspCantidadEstadosResult) {
            this.intspCantidadEstadosResult = intspCantidadEstadosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsagendamedicaWebChannel : Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsagendamedicaWebClient : System.ServiceModel.ClientBase<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb>, Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb {
        
        public WsagendamedicaWebClient() {
        }
        
        public WsagendamedicaWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsagendamedicaWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsagendamedicaWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsagendamedicaWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaCrearResponse Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb.indspRecetaCrear(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaCrearRequest request) {
            return base.Channel.indspRecetaCrear(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaCrearResult indspRecetaCrear(decimal piIndnuReporteId, System.DateTime piInddaFechaReceta, decimal piIndnuUsuarioId, decimal piIndnuCreadorId, string piIndvaIndicacionesArray) {
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaCrearRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaCrearRequest();
            inValue.piIndnuReporteId = piIndnuReporteId;
            inValue.piInddaFechaReceta = piInddaFechaReceta;
            inValue.piIndnuUsuarioId = piIndnuUsuarioId;
            inValue.piIndnuCreadorId = piIndnuCreadorId;
            inValue.piIndvaIndicacionesArray = piIndvaIndicacionesArray;
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaCrearResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb)(this)).indspRecetaCrear(inValue);
            return retVal.indspRecetaCrearResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaCrearResponse> Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb.indspRecetaCrearAsync(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaCrearRequest request) {
            return base.Channel.indspRecetaCrearAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaCrearResponse> indspRecetaCrearAsync(decimal piIndnuReporteId, System.DateTime piInddaFechaReceta, decimal piIndnuUsuarioId, decimal piIndnuCreadorId, string piIndvaIndicacionesArray) {
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaCrearRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaCrearRequest();
            inValue.piIndnuReporteId = piIndnuReporteId;
            inValue.piInddaFechaReceta = piInddaFechaReceta;
            inValue.piIndnuUsuarioId = piIndnuUsuarioId;
            inValue.piIndnuCreadorId = piIndnuCreadorId;
            inValue.piIndvaIndicacionesArray = piIndvaIndicacionesArray;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb)(this)).indspRecetaCrearAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaExpirarResponse Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb.indspRecetaExpirar(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaExpirarRequest request) {
            return base.Channel.indspRecetaExpirar(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaExpirarResult indspRecetaExpirar() {
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaExpirarRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaExpirarRequest();
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaExpirarResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb)(this)).indspRecetaExpirar(inValue);
            return retVal.indspRecetaExpirarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaExpirarResponse> Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb.indspRecetaExpirarAsync(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaExpirarRequest request) {
            return base.Channel.indspRecetaExpirarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaExpirarResponse> indspRecetaExpirarAsync() {
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaExpirarRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaExpirarRequest();
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb)(this)).indspRecetaExpirarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaIndicacionInsResponse Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb.indspRecetaIndicacionIns(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaIndicacionInsRequest request) {
            return base.Channel.indspRecetaIndicacionIns(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaIndicacionInsResult indspRecetaIndicacionIns(decimal piIndnuRecetaId, decimal piIndnuIndicacionesId, decimal piIndnuCreadorId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaIndicacionInsRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaIndicacionInsRequest();
            inValue.piIndnuRecetaId = piIndnuRecetaId;
            inValue.piIndnuIndicacionesId = piIndnuIndicacionesId;
            inValue.piIndnuCreadorId = piIndnuCreadorId;
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaIndicacionInsResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb)(this)).indspRecetaIndicacionIns(inValue);
            return retVal.indspRecetaIndicacionInsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaIndicacionInsResponse> Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb.indspRecetaIndicacionInsAsync(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaIndicacionInsRequest request) {
            return base.Channel.indspRecetaIndicacionInsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaIndicacionInsResponse> indspRecetaIndicacionInsAsync(decimal piIndnuRecetaId, decimal piIndnuIndicacionesId, decimal piIndnuCreadorId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaIndicacionInsRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaIndicacionInsRequest();
            inValue.piIndnuRecetaId = piIndnuRecetaId;
            inValue.piIndnuIndicacionesId = piIndnuIndicacionesId;
            inValue.piIndnuCreadorId = piIndnuCreadorId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb)(this)).indspRecetaIndicacionInsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaInsResponse Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb.indspRecetaIns(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaInsRequest request) {
            return base.Channel.indspRecetaIns(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaInsResult indspRecetaIns(decimal piIndnuReporteId, System.DateTime piInddaFechaReceta, decimal piIndnuUsuarioId, decimal piIndnuCreadorId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaInsRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaInsRequest();
            inValue.piIndnuReporteId = piIndnuReporteId;
            inValue.piInddaFechaReceta = piInddaFechaReceta;
            inValue.piIndnuUsuarioId = piIndnuUsuarioId;
            inValue.piIndnuCreadorId = piIndnuCreadorId;
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaInsResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb)(this)).indspRecetaIns(inValue);
            return retVal.indspRecetaInsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaInsResponse> Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb.indspRecetaInsAsync(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaInsRequest request) {
            return base.Channel.indspRecetaInsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaInsResponse> indspRecetaInsAsync(decimal piIndnuReporteId, System.DateTime piInddaFechaReceta, decimal piIndnuUsuarioId, decimal piIndnuCreadorId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaInsRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaInsRequest();
            inValue.piIndnuReporteId = piIndnuReporteId;
            inValue.piInddaFechaReceta = piInddaFechaReceta;
            inValue.piIndnuUsuarioId = piIndnuUsuarioId;
            inValue.piIndnuCreadorId = piIndnuCreadorId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb)(this)).indspRecetaInsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaRenovarResponse Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb.indspRecetaRenovar(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaRenovarRequest request) {
            return base.Channel.indspRecetaRenovar(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IndspRecetaRenovarResult indspRecetaRenovar(decimal piIndnuRecetaId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaRenovarRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaRenovarRequest();
            inValue.piIndnuRecetaId = piIndnuRecetaId;
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaRenovarResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb)(this)).indspRecetaRenovar(inValue);
            return retVal.indspRecetaRenovarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaRenovarResponse> Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb.indspRecetaRenovarAsync(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaRenovarRequest request) {
            return base.Channel.indspRecetaRenovarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaRenovarResponse> indspRecetaRenovarAsync(decimal piIndnuRecetaId) {
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaRenovarRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.indspRecetaRenovarRequest();
            inValue.piIndnuRecetaId = piIndnuRecetaId;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb)(this)).indspRecetaRenovarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.intspCantidadEstadosResponse Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb.intspCantidadEstados(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.intspCantidadEstadosRequest request) {
            return base.Channel.intspCantidadEstados(request);
        }
        
        public Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.IntspCantidadEstadosResult intspCantidadEstados(decimal piIntvaIdAgenda, System.DateTime piIntdaFechaInicio, System.DateTime piIntdaFechaFin, string piIntvaLstUsuarios, string piIntvaLstAreas) {
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.intspCantidadEstadosRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.intspCantidadEstadosRequest();
            inValue.piIntvaIdAgenda = piIntvaIdAgenda;
            inValue.piIntdaFechaInicio = piIntdaFechaInicio;
            inValue.piIntdaFechaFin = piIntdaFechaFin;
            inValue.piIntvaLstUsuarios = piIntvaLstUsuarios;
            inValue.piIntvaLstAreas = piIntvaLstAreas;
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.intspCantidadEstadosResponse retVal = ((Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb)(this)).intspCantidadEstados(inValue);
            return retVal.intspCantidadEstadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.intspCantidadEstadosResponse> Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb.intspCantidadEstadosAsync(Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.intspCantidadEstadosRequest request) {
            return base.Channel.intspCantidadEstadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.intspCantidadEstadosResponse> intspCantidadEstadosAsync(decimal piIntvaIdAgenda, System.DateTime piIntdaFechaInicio, System.DateTime piIntdaFechaFin, string piIntvaLstUsuarios, string piIntvaLstAreas) {
            Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.intspCantidadEstadosRequest inValue = new Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.intspCantidadEstadosRequest();
            inValue.piIntvaIdAgenda = piIntvaIdAgenda;
            inValue.piIntdaFechaInicio = piIntdaFechaInicio;
            inValue.piIntdaFechaFin = piIntdaFechaFin;
            inValue.piIntvaLstUsuarios = piIntvaLstUsuarios;
            inValue.piIntvaLstAreas = piIntvaLstAreas;
            return ((Alemana.Nucleo.Estadisticas.Servicio.WsAgendaMedica.WsagendamedicaWeb)(this)).intspCantidadEstadosAsync(inValue);
        }
    }
}
