//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alemana.Nucleo.Common.ExceptionHandling
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Messages.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {

        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alemana.Nucleo.Common.ExceptionHandling.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La accion no es válida.
        /// </summary>
        internal static string AccionNoValida {
            get {
                return ResourceManager.GetString("AccionNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar la configuración de manejo de excepciones del archivo de configuración.
        /// </summary>
        internal static string ErrorCargarSeccionManejoExcepcion {
            get {
                return ResourceManager.GetString("ErrorCargarSeccionManejoExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la acción de manejo de excepción no puede ser nulo o vacío.
        /// </summary>
        internal static string NombreAccionVacioONulo {
            get {
                return ResourceManager.GetString("NombreAccionVacioONulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la política no se corresponde a ninguno de los predefinidos: {0}.
        /// </summary>
        internal static string NombrePoliticaInvalida {
            get {
                return ResourceManager.GetString("NombrePoliticaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la política no existe entre las definidas en el archivo de configuración:.
        /// </summary>
        internal static string NombrePoliticaNoExiste {
            get {
                return ResourceManager.GetString("NombrePoliticaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro no puede ser null: {0}.
        /// </summary>
        internal static string ParametroNoPuedeSerNull {
            get {
                return ResourceManager.GetString("ParametroNoPuedeSerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La política \&quot;{0}\&quot; no tiene un tipo asociado a: {1}.
        /// </summary>
        internal static string PoliticaSinTipoAsociado {
            get {
                return ResourceManager.GetString("PoliticaSinTipoAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sección no existe en el archivo de configuración:.
        /// </summary>
        internal static string SeccionNoExiste {
            get {
                return ResourceManager.GetString("SeccionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo no hereda de System.Exception: .
        /// </summary>
        internal static string TipoNoHeredaDeException {
            get {
                return ResourceManager.GetString("TipoNoHeredaDeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo no es válido: {0}.
        /// </summary>
        internal static string TipoNoValido {
            get {
                return ResourceManager.GetString("TipoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo no puede ser vacío.
        /// </summary>
        internal static string TipoVacio {
            get {
                return ResourceManager.GetString("TipoVacio", resourceCulture);
            }
        }
    }
}
